- pxc-57/Dockerfile
- pxc-57/pxc-entry.sh
There where problems with the bash script pxc-entry.sh, which caused the initial database container to fail with "WSREP: Failed to resolve tcp://<myip>:4567".
Enhanced the "join" function to support uniq.
> Fixed problem "WSREP: Failed to resolve tcp://<myip>:4567"

- percona-server/README.md
- percona-server/ps-entry.sh
I've added some tests for a password file (MYSQL_ROOT_PASSWORD_FILE) that would be read for passwords upon startup. This adds the required functionality to support docker secrets when using Docker Swarm Mode.
> Support for Password Files added

- pxc-56/entrypoint.sh
- pxc-57/Dockerfile
This PR make the build more silent and adds support to MYSQL_ROOT_PASSWORD_FILE
to pxc-56
> Slient Build and added support to Docker Secrets pxc56

- percona-server.57/Dockerfile
- percona-server.57/Dockerfile-dockerhub
some users mount mysql configs to `/etc/mysql` dir.
after migration to centos - `/etc/mysql` dir become sym-link, due to docker behavior, configs become mounted to /etc dir (see https://github.com/moby/moby/issues/17944).
in result some files in `/etc` become unavailable (see https://github.com/presslabs/mysql-operator/pull/167)
> BLD-1195 fix config mount

- percona-server-mongodb.40/Dockerfile
testing perconalab/percona-server-mongodb:4.0.4
'utc' [1/6]...passed
'cve-2014--shellshock' [2/6]...passed
'no-hard-coded-passwords' [3/6]...passed
'override-cmd' [4/6]...passed
'mongo-basics' [5/6]...warning: the current Docker daemon does not appear to support seccomp
.passed
'mongo-auth-basics' [6/6]...warning: the current Docker daemon does not appear to support seccomp
.passed
> Lowcase rpm names

- percona-server-mongodb.40/Dockerfile
'utc' [1/6]...passed
'cve-2014--shellshock' [2/6]...passed
'no-hard-coded-passwords' [3/6]...passed
'override-cmd' [4/6]...passed
'mongo-basics' [5/6]...warning: the current Docker daemon does not appear to support seccomp
.passed
'mongo-auth-basics' [6/6]...warning: the current Docker daemon does not appear to support seccomp
..passed
> Set version due to latest decisions

- percona-server.57/ps-entry.sh
- percona-server.80/ps-entry.sh
- test/tests/mysql-conf-mount/conf.d/client.cnf
When the client is configured in `my.cnf`, and a password is specified, then MySQL initialization fails. This is a problem, now, because of the new image based on CenOS, that has the `/etc/my.cnf` file which includes all `*.cnf` files from `/etc/mysql`. Therefore `/etc/mysql/client.cnf` is loaded at initialization time, and the client fails to connect with the error:
```
2019-04-17T20:32:03.026406Z 3 [Note] Access denied for user 'root'@'localhost' (using password: YES)
MySQL init process in progress...
```
A solution is to explicitly specify the empty password to the MySQL client. Not sure if this covers all the cases,  there is another solution, to use `--no-defaults` client flag.
Thank you!
> Ignore password set in the .cnf file when first initializing MySQL

- percona-server-mongodb.36/ps-entry.sh
- percona-server-mongodb.40/ps-entry.sh
Kubernetes mongo operator can't start mongod in unsafe mode
due to the lack of sslMode option, which is not set by the
entrypoint script properly.
> CLOUD-220 Mongod ssl startup fix

- pxc-57/dockerdir/entrypoint.sh
Use case described in
https://www.percona.com/doc/percona-xtradb-cluster/LATEST/install/docker.html
did not comply with the current state of code.
Here is a small update for running cluster inside docker.
> CLOUD-337 Support use-case from doc

- percona-server.80/README.md
Updated the README.md. Fixed the grammar in the first paragraph. Changed the percona-server version to 8.0.15-6.
> PS-5628 README for percona-server.80 only shows pre-GA version

- percona-server-master-slave/master_nc
- percona-server-master-slave/ps-entry.sh
- pgr-57/clustercheckcron
- pgr-57/entrypoint.sh
- proxysql/dockerdir/usr/bin/add_cluster_nodes.sh
- pxc-56/clustercheckcron
- pxc-56/entrypoint.sh
- pxc-57/dockerdir/usr/bin/clustercheckcron
- pxc-57/dockerdir/usr/bin/configure-pxc.sh
From man pages: 
"-i, --ip-address Display the IP address(es) of the host. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead."
-I is shorthand for --all-ip-addresses.
> Change hostname -i to hostname -I

- pxc-57/Dockerfile
- pxc-57/Dockerfile.k8s
- pxc-57/dockerdir/etc/mysql/node.cnf
- pxc-57/dockerdir/usr/bin/clustercheck.sh
Since large db (>15GB) consumes a lot of time to obtain data
by the new pod the clustercheck script fails and breaks the pod.
Fix checks wheather the sst process is finished.
> CLOUD-376 Heavy DB upscale fix

- pxc-80/dockerdir/etc/mysql/node.cnf
This is needed to make ProxySQL work
> CLOUD-429: Use mysql_native_password

- pxc-57/dockerdir/entrypoint.sh
- test/detect-images.sh
According to https://jira.percona.com/browse/PXC-2168
> The problems seems to occur if you execute a writer operation too quickly after starting a Galera node - even bootstrapping a single node cluster with --wsrep-new-cluster. There seems to be a few millisecond race window between MySQL accepting connections and when Galera is actually initialized and won't abort queries with deadlock errors.
> We worked around in our environments by waiting for wsrep_local_state_comment == 'Synced' before attempting any node initialization which seems to have made our flakes go away in our (non-Docker) CI environments. We recently encountered a similar bug when running integration tests using the percona/percona-xtradb-cluster docker image - we think it's probably the same thing.
Basically I changed …
> wait for wsrep_local_state_comment to be Sync

- pxc-57/dockerdir/entrypoint.sh
Sorry for creating PR again - I accidentally discarded full output from mysql including selected value, but I should only discard stderr. I thought everything works since tests passed. This time I mounted my version of entrypoint and checked if it works before submitting PR. Sorry for the inconvenience.
> discard only stderr when waiting for database to by synced

- proxysql/Dockerfile
- proxysql/Dockerfile.k8s
just to confirm that it works:
```
+ CERT=/etc/proxysql/ssl/tls.crt
+ '[' -f /etc/proxysql/ssl-internal/tls.key ']'
+ '[' -f /var/run/secrets/kubernetes.io/serviceaccount/ca.crt ']'
+ '[' -f /etc/proxysql/ssl/tls.key ']'
+ '[' -f /etc/proxysql/ssl/ca.crt ']'
+ exec /usr/bin/proxysql -f -c /etc/proxysql/proxysql.cnf
2020-03-31 09:22:27 [INFO] Using config file /etc/proxysql/proxysql.cnf
2020-03-31 09:22:27 [INFO] Using OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
2020-03-31 09:22:27 [INFO] No SSL keys/certificates found in datadir (/var/lib/proxysql). Generating new keys/certificates.
2020-03-31 09:22:27 [INFO] ProxySQL version 2.0.10-percona-1.1
2020-03-31 09:22:27 [INFO] Detected OS: Linux fb2240170adf 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
2020-03-31 …
```
> [PSQLADM-237] Fix gnutls dependency

- .github/pr-badge.yml
- percona-server-mongodb.36/ps-entry.sh
- percona-server-mongodb.40/ps-entry.sh
- percona-server-mongodb.42/ps-entry.sh
[![K8SPSMDB-207](https://badgen.net/badge/JIRA/K8SPSMDB-207/green)](https://jira.percona.com/browse/K8SPSMDB-207)
Make ps-enty is generic, which will work with different mongodb versios
> K8SPSMDB-207: unify ps-entry.sh for different mongodb releases

- proxysql/dockerdir/entrypoint.sh
Makes possible to change the configuration "threads" under
section "mysql" from the default 2 via the environment variable
MYSQL_THREADS.
> Allow setting mysql-threads via MYSQL_THREADS

- proxysql/dockerdir/entrypoint.sh
Allow setting mysql-stacksize and mysql-interfaces via the
environment variables MYSQL_STACKSIZE and MYSQL_INTERFACES
respectively.
These together with mysql-threads are the only global variables
that take effect only after restarting ProxySQL. Therefore it
makes sennse to set them up before a ProxySQL instance first
starts.
Having the freedom to set these options this way allows for
easier scaling in Kubernetes for example.
> Proxysql config: mysql-stacksize, mysql-interfaces

- proxysql/dockerdir/etc/proxysql-admin.cnf
- proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-276](https://badgen.net/badge/JIRA/K8SPXC-276/green)](https://jira.percona.com/browse/K8SPXC-276)
how to test:
```
kubectl exec -it cluster1-proxysql-0 -- \
mysql -uproxyadmin -padmin_password -h127.0.0.1 -P 6032 \
-e "SELECT hostgroup_id,hostname,status FROM mysql_servers WHERE hostgroup_id=11;"
```
> K8SPXC-276 should have priority as writer in ProxySQL

- proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-344](https://badgen.net/badge/JIRA/K8SPXC-344/green)](https://jira.percona.com/browse/K8SPXC-344)
When Pod-0 is down, ProxySQL move traffic to the latest pod (Pod-2).
But, sometimes, Pod-0 (during fail) is not listed in the PXC service members.
Because of that, Pod-1 become the Writer for the proxysql-admin config.
in result we have many traffic switches, Pod-0 -> Pod-2, Pod-2 > Pod-1,
Pod-1 -> Pod-0.
> K8SPXC-344 writer always should point to pod-0

- pxc-57-backup/backup.sh
- pxc-80-backup/run_backup.sh
[![K8SPXC-347](https://badgen.net/badge/JIRA/K8SPXC-347/green)](https://jira.percona.com/browse/K8SPXC-347)
in some cases final md5 file size is less than 24kb.
according to reported issue by in K8SPXC-347, 23kb should be enoght.
> K8SPXC-347 adjust the minimal size for md5 file

- pxc-57-backup/recovery-pvc-joiner.sh
- pxc-57-backup/recovery-s3.sh
- pxc-80-backup/recovery-pvc-joiner.sh
- pxc-80-backup/recovery-s3.sh
[![K8SPXC-291](https://badgen.net/badge/JIRA/K8SPXC-291/green)](https://jira.percona.com/browse/K8SPXC-291)
kubernetes node can have root partition smaller than datadir partition.
in such case backup will be failed.
> K8SPXC-291 put tmpdir into datadir

- pxc-57-backup/recovery-pvc-joiner.sh
- pxc-57-backup/recovery-s3.sh
PXB 2.4 doesn't support lz4 compression so xbstream doesn't have `--decompress` option.
Some tests on 5.7 were failing like this:
```
$ k logs restore-job-on-demand-backup-pvc-one-pod-zsv9x
+ LIB_PATH=/usr/lib/pxc
+ . /usr/lib/pxc/check-version.sh
+ . /usr/lib/pxc/vault.sh
++ set -o errexit
++ keyring_vault=/etc/mysql/vault-keyring-secret/keyring_vault.conf
+ SOCAT_OPTS=TCP:restore-src-on-demand-backup-pvc-one-pod:3307,retry=30
+ check_ssl
+ CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+ '[' -f /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt ']'
+ SSL_DIR=/etc/mysql/ssl
+ '[' -f /etc/mysql/ssl/ca.crt ']'
+ SSL_INTERNAL_DIR=/etc/mysql/ssl-internal
+ '[' -f /etc/mysql/ssl-internal/ca.crt ']'
+ KEY=/etc/mysql/ssl/tls.key
+ CERT=/etc/mysql/ssl/tls.crt
+ '[' -f …
```
> Remove --decompress option for xbstream in PXC 5.7 backup images

- percona-server-mongodb-4.2/README.md
The default port of MongoDB 27017, not 3306 (MySQL/MariaDB default port), this PR changes the Docker CLI example in the README.
> Replace 3306 port to 27017 port in docker CLI example

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-464](https://badgen.net/badge/JIRA/K8SPXC-464/green)](https://jira.percona.com/browse/K8SPXC-464)
* add usage of 'pc.weight' option to avoid situation
when pxc node becomes non-primary when backup via garbd
fails for one pod installation
> K8SPXC-464 add usage of 'pc.weight' option

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-370](https://badgen.net/badge/JIRA/K8SPXC-370/green)](https://jira.percona.com/browse/K8SPXC-370)
Reverts percona/percona-docker#310
> Revert "K8SPXC-438 add possibility to use 32 symbols for cluster name"

- proxysql/dockerdir/entrypoint.sh
- proxysql/dockerdir/etc/proxysql-admin.cnf
[![K8SPXC-553](https://badgen.net/badge/JIRA/K8SPXC-553/green)](https://jira.percona.com/browse/K8SPXC-553)
* for PXCO we need to use 'yes' (by default it is 'backup')
as a defult value for 'WRITERS_ARE_READERS' option to add
all writers to read hostgroup
> K8SPXC-553 use 'yes' as a default value for 'WRITERS_ARE_READERS'

- percona-xtradb-cluster-5.7-backup/Dockerfile
PS_VERSION most probably should be the same as PXC_VERSION because it selects shared/shared-compat packages which will be installed.
> Fix PS version in PXC 5.7 backup image

- percona-xtradb-cluster-8.0-backup/recovery-pvc-joiner.sh
- percona-xtradb-cluster-8.0-backup/recovery-s3.sh
Seems that PXB 8.0 doesn't have `binlog-info` option and is throwing warning like below.
I'm not going to rebuild backup images for this since just a warning, but it might be good to cleanup this.
```
+ xtrabackup  --prepare --binlog-info=ON --rollback-prepared-trx     --xtrabackup-plugin-dir=/usr/lib64/xtrabackup/plugin --target-dir=/datadir/pxc_sst_nybk
xtrabackup: recognized server arguments: --innodb_checksum_algorithm=crc32 --innodb_log_checksums=1 --innodb_data_file_path=ibdata1:12M:autoextend --innodb_log_files_in_group=2 --innodb_log_file_size=50331648 --innodb_page_size=16384 --innodb_undo_directory=./ --innodb_undo_tablespaces=2 --server-id=10 --innodb_log_checksums=ON --innodb_redo_log_encrypt=0 --innodb_undo_log_encrypt=0
xtrabackup: recognized client arguments: --prepare=1 …
```
> Remove binlog-info for PXC 8.0 backup since PXB 8.0 doesn't have it

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-430](https://badgen.net/badge/JIRA/K8SPXC-430/green)](https://jira.percona.com/browse/K8SPXC-430) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* use 'pc.weight=0' for garbd backup process in this case
'garbd' will be allowed to take a backup without
participation in the quorum calculations
> K8SPXC-430 use 'pc.weight=0' for garbd

- percona-xtradb-cluster-5.7-backup/Dockerfile
- percona-xtradb-cluster-5.7/Dockerfile
- percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-3629](https://badgen.net/badge/JIRA/PXC-3629/green)](https://jira.percona.com/browse/PXC-3629) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
@delgod, @hors 
Here are test docker images 
perconalab/percona-xtradb-cluster:5.7.33-31.49-backup
perconalab/percona-xtradb-cluster:5.7.33-31.49
Could someone use them in the tests you have to verify if all works correctly after removing PS packages from PXC images?
> PXC-3629 remove ps dependency from pxc docker

- haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
haproxy version was bumped from `2.1.x` to `2.3.2` which introduces some new options and hardening so some tests and probes were failing.
Some info: https://www.haproxy.com/blog/announcing-haproxy-2-2/#security-hardening
I have executed the `users` test locally with the custom image (`plavi/test:test-haproxy`) and it passed.
Error: 
```
│ [ALERT] 092/171857 (7) : Failed to fork process for external health check (likely caused by missing 'insecure-fork-wanted'): Resource temporarily unavailable. Aborting.                                         │
│ [ALERT] 092/171858 (7) : Failed to fork process for external health check (likely caused by missing 'insecure-fork-wanted'): Resource temporarily unavailable. Aborting.                                         │
│ [ALERT] 092/171859 (7) : Failed …
```
> Add insecure-fork-wanted option to haproxy

- percona-server-8.0/ps-entry.sh
When running mysqlsh clusterAddInstance to create a cluster the
following warnings are added to the output of mysqlsh
This change turns off SQL_BIN_LOG so that the GTID is not generated by
the initial tzinfo insert statements.
```
WARNING: A GTID set check of the MySQL instance at 'hostname.svc.cluster.local:3306' determined that it contains transactions that do not originate from the cluster, which must be discarded before it can join the cluster.
hostname.svc.cluster.local:3306 has the following errant GTIDs that do not exist in the cluster:
c8ee89a9-840a-11eb-8a25-0242ac11000b:1-5
```
We only made this change to the percona-server-8.0 entry point. Let us know to which other images this change should be added.
Co-authored-by: David Sharp <dsharp@vmware.com>
Co-authored-by: Colin Shield …
> entrypoint: Disable binlog while loading tzinfo

- percona-server-mongodb-4.4/Dockerfile
I got the error that there is no "/js-yaml.js" when supplying a mongod.conf as an argument. See entrypoint.sh line 192.
You should add jsyaml in some way. The proposed change is just one solution to supply that file, which might not be ideal.
> Fetch dependency js-yaml

- proxysql/dockerdir/etc/proxysql/proxysql.cnf
[![K8SPXC-900](https://badgen.net/badge/JIRA/K8SPXC-900/green)](https://jira.percona.com/browse/K8SPXC-900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* starting from 2.1.0 proxysql started to sync mysql and admin
variables by default, to have possibility of using custom
config for proxysql we need to disable it. Users can enable
it if needed via custom config feature
> K8SPXC-900 disable syncing of mysql and admin variables

- orchestrator/dockerdir/entrypoint.sh
Allow to disable raft for the orchestrator. As for now PS Operator does not allow to run multiple orchestrator instances
> Allow to disable raft for the orchestrator

- postgresql-containers/bin/postgres-ha/common/pgha-reload-local.sh
This was referencing an older directory. This would likely
cause just some noise and not any actual functional issues.
> Merge 4.7.4 Fix sourcing common libs in reload script

- percona-server-mongodb-4.2/Dockerfile.debug
- percona-server-mongodb-4.2/Dockerfile.ubi8
Docker official images should be based on other official images,
so reverting FROM from UBI 8 to CentOS 8.
> [ENG-1065] Docker Official image for PSMDB-4.2

- percona-server-mongodb-4.4/Dockerfile.debug
- percona-server-mongodb-4.4/Dockerfile.ubi8
Docker official images should be based on other official images,
so reverting FROM from UBI 8 to CentOS 8.
> [ENG-1065] Docker Official image for PSMDB-4.4

- percona-xtradb-cluster-5.7/Dockerfile
- percona-xtradb-cluster-5.7/Dockerfile.k8s
- percona-xtradb-cluster-8.0/Dockerfile
- percona-xtradb-cluster-8.0/Dockerfile.k8s
socat 1.7.3.3 has issues with SSL transfers causing cluster
bootstraps to fail, it seems the backup image was updated
however the main images were not due to another blocker
that has since been resolved[1].
[1]: https://jira.percona.com/browse/PXC-3679
> Upgrade socat to 1.7.4

- proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-835](https://badgen.net/badge/JIRA/K8SPXC-835/green)](https://jira.percona.com/browse/K8SPXC-835) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* we had a limitation that proxysql can't be used with
replica cluster due to limitation on proxyadmin end. It
was improved and now we can fix it on our end too.
If --update-cluster is used with the --force flag,
a warning will be issued (instead of an error) if the
write-node is a read-only node.
> K8SPXC-835 add possibly of using proxysql in replica cluster

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-1042](https://badgen.net/badge/JIRA/K8SPXC-1042/green)](https://jira.percona.com/browse/K8SPXC-1042) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* avoid 'syntax error' in backup.sh in case of not getting
cluster size
> K8SPXC-1042 fix 'syntax error' in backup.sh

- proxysql/dockerdir/usr/bin/add_proxysql_nodes.sh
- proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-1059](https://badgen.net/badge/JIRA/K8SPXC-1059/green)](https://jira.percona.com/browse/K8SPXC-1059) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Now, mysql passwd is print in the proxysql pod log. It is not safe
> K8SPXC-1059 - remove password print

- haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
[![CLOUD-734](https://badgen.net/badge/JIRA/CLOUD-734/green)](https://jira.percona.com/browse/CLOUD-734) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
`http-use-htx` was deprecated and is now removed and used by default so haproxy doesn't want to start: https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4-option%20http-use-htx
`Since the version 2.0-dev3, the HTX is the default mode.`
> CLOUD-734 - HAProxy - remove deprecated option http-use-htx

- proxysql/dockerdir/entrypoint.sh
[![K8SPXC-1038](https://badgen.net/badge/JIRA/K8SPXC-1038/green)](https://jira.percona.com/browse/K8SPXC-1038) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Remove the `if` because it was always `true` before this change https://github.com/percona/percona-docker/commit/20c2deea12185ca9f161bc05ab14aa252772864c (variable was not quoted), so when we changed [] to [[]] the `if` started filtering and executing conditionally which broke proxysql in our operator images.
This is how we had it set in operator 1.11.0 running images:
```
$ k exec cluster1-proxysql-0 -c proxysql -- env|grep …
```
> K8SPXC-1038 - Fix entrypoint for proxysql

- proxysql/Dockerfile.k8s
* we can remove it because operator does not use it for now
> fix CVE in pxc_scheduler_handler bin file

- percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh
[![K8SPXC-1157](https://badgen.net/badge/JIRA/K8SPXC-1157/green)](https://jira.percona.com/browse/K8SPXC-1157) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* PXB has a [bug](https://jira.percona.com/browse/PXB-1854) and it can't delete 'md5sum' file. When mc tries to understand whether the old backup exists or not it detects this md5sum file and thinks that the backup exists and it is needed to delete it. So, we need to check a dir.
> K8SPXC-1157 fix removing of the old backup

- percona-distribution-postgresql-11/README.md
- percona-distribution-postgresql-12/README.md
- percona-distribution-postgresql-13/README.md
- percona-distribution-postgresql-14/README.md
- percona-distribution-postgresql-15/README.md
[![DISTPG-521](https://badgen.net/badge/JIRA/DISTPG-521/green)](https://jira.percona.com/browse/DISTPG-521) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The --link option is deprecated. Moreover, using it throws errors. Updated the section to use the --network option
> DISTPG-521 Updated the Connect from another app section

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-989](https://badgen.net/badge/JIRA/K8SPXC-989/green)](https://jira.percona.com/browse/K8SPXC-989) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* in case if dual stack (node can have IPv6 and IPv4 IPs) we need to get only IPv4 because operator does not support IPv6
> K8SPXC-989 use IPv4 only

- haproxy/Dockerfile
[![K8SPXC-1252](https://badgen.net/badge/JIRA/K8SPXC-1252/green)](https://jira.percona.com/browse/K8SPXC-1252) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* krb5-libs  ubi 9 image base image has it, and we do not need to install it
> K8SPXC-1252 remove installing of krb5-libs rpm from Dockerfile

- fluentbit/Dockerfile
issue:
```
package krb5-libs-1.18.2-25.el8_8.x86_64 (which is newer than krb5-libs-1.18.2-22.0.1.el8_7.x86_64) is already installed
```
> Remove krb5-libs.rpm installation from fluentbit image

- haproxy/dockerdir/entrypoint.sh
- haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
- haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
- haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-1276](https://badgen.net/badge/JIRA/K8SPXC-1276/green)](https://jira.percona.com/browse/K8SPXC-1276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR fix two issues that were described in K8SPXC-1276 and in K8SPXC-1277
```
> kubectl logs cluster1-haproxy-2 -c haproxy -f
{"time":"24/Jul/2023:14:19:33.050", "backend_source_ip": "10.72.1.20", "backend_source_port": "33062", "message": "The following values are used for PXC node 10.72.1.20 in backend galera-mysqlx-nodes:"}
{"time":"24/Jul/2023:14:19:33.053", "backend_source_ip": "10.72.1.20", "backend_source_port": "33062", …
```
> K8SPXC-1276 add logformat for haproxy container

- mysql-router/Dockerfile
[![DISTMYSQL-345](https://badgen.net/badge/JIRA/DISTMYSQL-345/green)](https://jira.percona.com/browse/DISTMYSQL-345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> DISTMYSQL-345-MySQL-Router-8.0.33-image-is-missing-from-dockerhub

- percona-backup-mongodb/Dockerfile.aarch64
- percona-backup-mongodb/start-agent.sh
[![PBM-1138](https://badgen.net/badge/JIRA/PBM-1138/green)](https://jira.percona.com/browse/PBM-1138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
PBM docker image for ARM arch doesn't contain MongoDB CLI (neither old-style one, nor new mongosh) since PSMDB packages for ARM are built for EL8, while PBM package was built for EL9.
> PBM-1138. Add dockerfile for PBM arm64

- proxysql/Dockerfile
- proxysql/Dockerfile.k8s
proxysql container is currently failing builds with:
```
package krb5-libs-1.18.2-25.el8_8.x86_64 (which is newer than krb5-libs-1.18.2-22.0.1.el8_7.x86_64) is already installed
```
> Use krb5-libs from distro in proxysql build

- percona-xtradb-cluster-5.7/Dockerfile
- percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-4333](https://badgen.net/badge/JIRA/PXC-4333/green)](https://jira.percona.com/browse/PXC-4333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Build is failing with:
```
19:05:45  [0m[91m	package krb5-libs-1.18.2-25.el8_8.x86_64 (which is newer than krb5-libs-1.18.2-22.0.1.el8_7.x86_64) is already installed
19:05:45  [0mThe command '/bin/sh -c set -ex;     curl -Lf -o /tmp/numactl-libs.rpm http://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/numactl-libs-2.0.12-13.el8.x86_64.rpm;     curl -Lf -o /tmp/libev.rpm http://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/ …
```
> PXC-4333 - Fix PXC 5.7 build for krb5-libs package

- percona-server-mongodb-7.0/Dockerfile.debug
- percona-server-mongodb-7.0/Dockerfile.k8s
[![ENG-7](https://badgen.net/badge/JIRA/ENG-7/green)](https://jira.percona.com/browse/ENG-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
percona-server-mongodb-debugsource pkg is not created for PSMDB-70 so should be removed from Docker files
[ENG-7]: https://perconadev.atlassian.net/browse/ENG-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-7 remove psmdb-dbgsrc pkg from psmdb-70 dockers

- percona-server-mongodb-4.2/Dockerfile
- percona-server-mongodb-4.2/Dockerfile.debug
- percona-server-mongodb-4.2/Dockerfile.k8s
- percona-server-mongodb-4.2/Dockerfile.ubi8
- percona-server-mongodb-4.2/ps-entry.sh
[![PSMDB-1362](https://badgen.net/badge/JIRA/PSMDB-1362/green)](https://jira.percona.com/browse/PSMDB-1362) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1362]: https://perconadev.atlassian.net/browse/PSMDB-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PSMDB-1362. Add call home.sh script to PSMDB docker image

- fluentbit/Dockerfile
[![K8SPXC-1295](https://badgen.net/badge/JIRA/K8SPXC-1295/green)](https://jira.percona.com/browse/K8SPXC-1295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPXC-1295 Update Fluent Bit Dockerfile to use newer versions of UBI and Percona

- percona-server-mongodb-6.0/Dockerfile
- percona-server-mongodb-6.0/Dockerfile.aarch64
- percona-server-mongodb-6.0/Dockerfile.k8s
- percona-server-mongodb-6.0/Dockerfile.ubi8
- percona-server-mongodb-6.0/Dockerfile.ubi9
- test/tests/mongo-basics/run.sh
[![PSMDB-1429](https://badgen.net/badge/JIRA/PSMDB-1429/green)](https://jira.percona.com/browse/PSMDB-1429) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1429]: https://perconadev.atlassian.net/browse/PSMDB-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PSMDB-1429. Update psmdb-6.0 version

- postgresql-containers/build/pgbackrest/Dockerfile
[![K8SPG-547](https://badgen.net/badge/JIRA/K8SPG-547/green)](https://jira.percona.com/browse/K8SPG-547) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
pgbackrest 2.50 requires libssh2.so.1, which requires epel.
```
$ diff --color <(rpm -qR percona-pgbackrest-2.48-1.el8.x86_64.rpm 2>&1) <(rpm -qR percona-pgbackrest-2.50-1.el8.x86_64.rpm 2>&1)
1,2c1,2
< warning: percona-pgbackrest-2.48-1.el8.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 8507efa5: NOKEY
< config(percona-pgbackrest) = 1:2.48-1.el8
---
> warning: percona-pgbackrest-2.50-1.el8.x86_64.rpm: Header V4 RSA/SHA256 …
```
> K8SPG-547: pgbackrest container can't use pgbackrest 2.50

- postgresql-containers/build/pgbackrest-repo/Dockerfile
[![K8SPG-547](https://badgen.net/badge/JIRA/K8SPG-547/green)](https://jira.percona.com/browse/K8SPG-547) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-547]: https://perconadev.atlassian.net/browse/K8SPG-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-547 pgbackrest container can't use pgbackrest 2.50 for repo image

- percona-backup-mongodb/Dockerfile
- percona-backup-mongodb/Dockerfile.aarch64
- percona-backup-mongodb/Dockerfile.ubi8
- percona-backup-mongodb/Dockerfile.ubi9
[![CVE-2024](https://badgen.net/badge/JIRA/CVE-2024/green)](https://jira.percona.com/browse/CVE-2024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> PBM. Update kubectl to avoid CVE-2024-24790

- postgresql-containers/build/pgbackrest-repo/Dockerfile
- postgresql-containers/build/pgbackrest/Dockerfile
[![K8SPG-604](https://badgen.net/badge/JIRA/K8SPG-604/green)](https://jira.percona.com/browse/K8SPG-604) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-604]: https://perconadev.atlassian.net/browse/K8SPG-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-604 percona-pgbackrest rpm creats postgres user 

- haproxy/Dockerfile
[![PXC-4482](https://badgen.net/badge/JIRA/PXC-4482/green)](https://jira.percona.com/browse/PXC-4482) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4482]: https://perconadev.atlassian.net/browse/PXC-4482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXC-4482 Release and packaging tasks for PXC-8.0.37

- percona-backup-mongodb/Dockerfile.aarch64
[![PBM-1396](https://badgen.net/badge/JIRA/PBM-1396/green)](https://jira.percona.com/browse/PBM-1396) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1396]: https://perconadev.atlassian.net/browse/PBM-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBM-1396. Use ubi8 as base image for PBM ARM docker

- percona-backup-mongodb/Dockerfile
- percona-backup-mongodb/Dockerfile.aarch64
- percona-backup-mongodb/Dockerfile.ubi8
- percona-backup-mongodb/Dockerfile.ubi9
- percona-backup-mongodb/LICENSE
[![PBM-1441](https://badgen.net/badge/JIRA/PBM-1441/green)](https://jira.percona.com/browse/PBM-1441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
For RedHat's certification it's required to add license to PBM images, the license was taken from https://github.com/percona/percona-backup-mongodb/blob/dev/LICENSE
[PBM-1441]: https://perconadev.atlassian.net/browse/PBM-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBM-1441. Add licenses to PBM image

- postgresql-containers/build/pgbackrest/Dockerfile
- postgresql-containers/build/postgres/Dockerfile
[![K8SPG-652](https://badgen.net/badge/JIRA/K8SPG-652/green)](https://jira.percona.com/browse/K8SPG-652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-652]: https://perconadev.atlassian.net/browse/K8SPG-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-652 upstream operator does not support pgbackrest 2.54

- percona-server-mongodb-6.0/Dockerfile
- percona-server-mongodb-6.0/Dockerfile-dockerhub
- percona-server-mongodb-6.0/Dockerfile.aarch64
- percona-server-mongodb-6.0/Dockerfile.debug
- percona-server-mongodb-6.0/Dockerfile.k8s
- percona-server-mongodb-7.0/Dockerfile
- percona-server-mongodb-7.0/Dockerfile-dockerhub
- percona-server-mongodb-7.0/Dockerfile.aarch64
- percona-server-mongodb-7.0/Dockerfile.debug
- percona-server-mongodb-7.0/Dockerfile.k8s
- percona-server-mongodb-7.0/Dockerfile.ubi9
- percona-server-mongodb-8.0/Dockerfile
- percona-server-mongodb-8.0/Dockerfile-dockerhub
- percona-server-mongodb-8.0/Dockerfile.aarch64
- percona-server-mongodb-8.0/Dockerfile.debug
- percona-server-mongodb-8.0/Dockerfile.k8s
- percona-server-mongodb-8.0/Dockerfile.ubi9
[![PKG-285](https://badgen.net/badge/JIRA/PKG-285/green)](https://jira.percona.com/browse/PKG-285) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Reverts percona/percona-docker#1088
[PKG-285]: https://perconadev.atlassian.net/browse/PKG-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "[PKG-285] + [PKG-287] + [PKG-290]: UBI 9 base images for PS MongoDB 6/7/8."

- percona-xtradb-cluster-8.0/Dockerfile
- percona-xtradb-cluster-8.0/Dockerfile.aarch64
- percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PKG-232](https://badgen.net/badge/JIRA/PKG-232/green)](https://jira.percona.com/browse/PKG-232) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-232]: https://perconadev.atlassian.net/browse/PKG-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKG-232 Packaging tasks for release - PXC 8.4.3

- percona-backup-mongodb/Dockerfile
- percona-backup-mongodb/Dockerfile.aarch64
[![PBM-1476](https://badgen.net/badge/JIRA/PBM-1476/green)](https://jira.percona.com/browse/PBM-1476) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Labels included in base images are inherited, so it's required to override the existing maintainer label. The value is set the same as in other products.
[PBM-1476]: https://perconadev.atlassian.net/browse/PBM-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBM-1476. Override maintainer label included in base image

- percona-xtradb-cluster-5.7/Dockerfile-pro
[![PKG-234](https://badgen.net/badge/JIRA/PKG-234/green)](https://jira.percona.com/browse/PKG-234) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-234]: https://perconadev.atlassian.net/browse/PKG-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKG-234 Packaging tasks for release - PXC 5.7 EOL

- postgresql-containers/build/postgres/Dockerfile
Based on Docker documentation `dockerfile-upstream:master` has all the latest fixes and can be unstable. Usage of  latest released is more recommended `syntax=docker/dockerfile:1`.
> Use more stable syntax dockerfile:1 instead of master

- mysql-router/Dockerfile
- percona-xtradb-cluster-8.0/Dockerfile
- percona-xtradb-cluster-8.0/Dockerfile.aarch64
[![PKG-461](https://badgen.net/badge/JIRA/PKG-461/green)](https://jira.percona.com/browse/PKG-461) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-461]: https://perconadev.atlassian.net/browse/PKG-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKG-461 mysql-router Dockerfile file is outdated and needs to be fixed

- percona-xtradb-cluster-8.4/Dockerfile
- percona-xtradb-cluster-8.4/dockerdir/etc/mysql/node.cnf
- percona-xtradb-cluster-8.4/dockerdir/usr/lib64/mysql/plugin/component_keyring_vault.cnf
- percona-xtradb-cluster-8.4/dockerdir/usr/sbin/mysqld.my
[![K8SPXC-1511](https://badgen.net/badge/JIRA/K8SPXC-1511/green)](https://jira.percona.com/browse/K8SPXC-1511) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1511]: https://perconadev.atlassian.net/browse/K8SPXC-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPXC-1511: Add global manifests for keyring vault component

- percona-xtradb-cluster-5.7-backup/backup.sh
- percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh
- percona-xtradb-cluster-8.4-backup/lib/pxc/backup.sh
[![K8SPXC-1475](https://badgen.net/badge/JIRA/K8SPXC-1475/green)](https://jira.percona.com/browse/K8SPXC-1475) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
In the PR we introduce a fix for the checking of the existence of backup objects in Azure storage. We are slightly refactoring the logic so that instead of querying the whole storage and then grepping the response for the searched object, we use URL params with our object prefix and search the response for non-empty blobs. The problem of fetching the whole storage space and then using grep, is that Azure API is paginating the …
> K8SPXC-1475 fix azure check for existing object

- percona-xtradb-cluster-5.7-backup/lib/pxc/aws.sh
- percona-xtradb-cluster-8.0-backup/lib/pxc/aws.sh
- percona-xtradb-cluster-8.4-backup/lib/pxc/aws.sh
[![K8SPXC-1475](https://badgen.net/badge/JIRA/K8SPXC-1475/green)](https://jira.percona.com/browse/K8SPXC-1475) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
@eleo007 noticed that when we are running the following on 5.7
```
aws s3 ls s3://operator-testing/demand-backup-cloud-2025-04-08-19:22:29-full.sst_info --summarize
```
We get `Total Objects: 0`, and the tests are failing even through that the objects and the directories exist in S3. 
We add to the aforementioned command the `--recursive` option so that the path is treated as a prefix, listing everything with the same prefix and …
> K8SPXC-1475 s3 ls uses --recursive

- haproxy/Dockerfile
- orchestrator/Dockerfile
[![K8SPS-418](https://badgen.net/badge/JIRA/K8SPS-418/green)](https://jira.percona.com/browse/K8SPS-418) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-418
`haproxy` and `orchestrator` use the `SIGTERM` signal for graceful termination
[K8SPS-418]: https://perconadev.atlassian.net/browse/K8SPS-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPS-418: remove SIGUSR1 stop signal

- percona-xtradb-cluster-8.0/Dockerfile
- percona-xtradb-cluster-8.0/Dockerfile.aarch64
- percona-xtradb-cluster-8.4/Dockerfile
- percona-xtradb-cluster-8.4/Dockerfile.aarch64
[![K8SPXC-1628](https://badgen.net/badge/JIRA/K8SPXC-1628/green)](https://jira.percona.com/browse/K8SPXC-1628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1628
Added libtcmalloc to PXC Docker images.
[K8SPXC-1628]: https://perconadev.atlassian.net/browse/K8SPXC-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPXC-1628: Allow tcmalloc as alternative in PXC images

- percona-pgbackrest/Dockerfile
- percona-pgbouncer/Dockerfile
[![K8SPG-613](https://badgen.net/badge/JIRA/K8SPG-613/green)](https://jira.percona.com/browse/K8SPG-613) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Operator requires `pkill` in pgbackrest and pgboucer images.
> K8SPG-613: add procps-ng (pkill) in official pgbackrest and pgboucer
