percona/percona-docker

README.md
=> changes made to README.md for help using container

percona-server-mongodb.32/Dockerfile, percona-server-mongodb.34/Dockerfile, percona-server-mongodb.34/README-build.md, percona-server-mongodb.34/README.md, percona-server-mongodb.34/ps-entry.sh
What was done
-reworked psmdb-30. now image is created for jessie
-reworked psmdb-32. now image is created for jessie
-created infrastructure for psmdb34 based on psmdb-34-beta packages
=> Percona-Server-MongoDB changes

percona-server-mongodb.34/Dockerfile
The image doesn't build currently.
=> Fix in PSMDB 3.4 Dockerfile typo in FROM clause

pxc-57/Dockerfile, pxc-57/entrypoint.sh
This PR make the build more silent and adds support to MYSQL_ROOT_PASSWORD_FILE
=> Slient Build and added support to Docker Secrets

pxc-57/entrypoint.sh
-"sort -un" removes lines that begins with the same number, for example
10.200.1.1 would be the same as 10.254.13.23.
-to remove our own ipaddr is better to use // as the string replacement
operator, because if the container restarted less than 60 seconds ago
our own ip will be in the queue list more than one time and will only
be removed one time.
=> minor fixes in pxc-57/entrypoint.sh

build_scripts/docker_builder.sh
This script could be started on jessie VM and do the following:
-Installs docker
-build docker image
-save it
-load it
-checks if docker is running
Please note that during script execution ALL dockers(images and containers)
on the system will be removed. So be carefull!
=> Add script which could build docker images on jessie VMs

percona-server.56/Dockerfile, percona-server.56/ps-entry.sh, percona-server.57/Dockerfile, percona-server.57/ps-entry.sh, percona-server.80/Dockerfile, percona-server.80/ps-entry.sh
It is better to open and look each commit separately.
Commit https://github.com/percona/percona-docker/commit/e2bb661944dbc303db93da943fc11b1bafe535ae has only tabulation changes, can be verified by `git sh -w e2bb661` command
=> Merge official docker image changes

percona-server.56/Dockerfile, percona-server.56/ps-entry.sh, percona-server.57/Dockerfile, percona-server.57/ps-entry.sh, percona-server.80/Dockerfile, percona-server.80/ps-entry.sh
as usual simpler to look each commit separately
=> Merge docker library changes

percona-server-mongodb.36/Dockerfile, percona-server-mongodb.36/ps-entry.sh
as usual, it is better to look each commit separately
=> CLOUD-22 add operator changes

percona-server-mongodb.34/Dockerfile, percona-server-mongodb.34/ps-entry.sh
merge upstream entrypoint.sh
main goal: add authentication support
=> CLOUD-39 add auth for MongoDB 3.4

pxc-57/dockerdir/usr/bin/configure-pxc.sh
fix after https://github.com/percona/percona-docker/pull/118
=> fix hostname output

percona-server-mongodb.36/Dockerfile, percona-server-mongodb.36/Dockerfile.k8s, percona-server-mongodb.40/Dockerfile, percona-server-mongodb.40/Dockerfile.k8s, percona-server-mongodb.42/Dockerfile, percona-server-mongodb.42/Dockerfile.k8s
Add debug build tag to psmdb dockerfiles to install additional tools for debugging MongoDB
=> K8SPSMDB-133: Add debug container to percona-server-mongodb

percona-server-mongodb.36/ps-entry.sh, percona-server-mongodb.40/ps-entry.sh, percona-server-mongodb.42/ps-entry.sh
[![K8SPSMDB-207](https://badgen.net/badge/JIRA/K8SPSMDB-207/green)](https://jira.percona.com/browse/K8SPSMDB-207)
=> K8SPSMDB-207 Fix typo

proxysql/dockerdir/entrypoint.sh, proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-252](https://badgen.net/badge/JIRA/K8SPXC-252/green)](https://jira.percona.com/browse/K8SPXC-252)
=> K8SPXC-252 Change root to monitor user

pxb-80/Dockerfile
[![PXB-2200](https://badgen.net/badge/JIRA/PXB-2200/green)](https://jira.percona.com/browse/PXB-2200)
=> PXB-2200: Update PXB80 to 8.0.13

pxc-80-backup/Dockerfile, pxc-80/Dockerfile, pxc-80/Dockerfile.k8s
[![PXC-3315](https://badgen.net/badge/JIRA/PXC-3315/green)](https://jira.percona.com/browse/PXC-3315)
=> PXC-3315 Update pxc-80 version

pxc-80-backup/Dockerfile, pxc-80-backup/backup.sh, pxc-80-backup/run_backup.sh
[![K8SPXC-242](https://badgen.net/badge/JIRA/K8SPXC-242/green)](https://jira.percona.com/browse/K8SPXC-242)
=> K8SPXC-242 Stabilize pxc backups

percona-server-mongodb.36/Dockerfile, percona-server-mongodb.36/Dockerfile.k8s, percona-server-mongodb.40/Dockerfile, percona-server-mongodb.40/Dockerfile.k8s, percona-server-mongodb.42/Dockerfile, percona-server-mongodb.42/Dockerfile.k8s, proxysql/Dockerfile, proxysql/Dockerfile.k8s, pxc-57-backup/Dockerfile, pxc-57/Dockerfile, pxc-57/Dockerfile.k8s
[![K8SPXC-242](https://badgen.net/badge/JIRA/K8SPXC-242/green)](https://jira.percona.com/browse/K8SPXC-242)
=> K8SPXC-242  Update  version for jq and oniguruma rpms

percona-toolkit/Dockerfile
[![PT-1858](https://badgen.net/badge/JIRA/PT-1858/green)](https://jira.percona.com/browse/PT-1858)
=> PT-1858: Add Percona-Toolkit containers

pxc-57-backup/recovery-pvc-joiner.sh, pxc-57-backup/recovery-s3.sh, pxc-80-backup/recovery-pvc-joiner.sh, pxc-80-backup/recovery-s3.sh
[![K8SPXC-280](https://badgen.net/badge/JIRA/K8SPXC-280/green)](https://jira.percona.com/browse/K8SPXC-280)
Corresponding change in operator scripts repo is here: https://github.com/percona/percona-xtradb-cluster-operator/pull/421
=> K8SPXC-280 Add decompress option to xbstream to support compressed backups

percona-server-mongodb.40/Dockerfile, percona-server-mongodb.40/Dockerfile.k8s
[![PSMDB-605](https://badgen.net/badge/JIRA/PSMDB-605/green)](https://jira.percona.com/browse/PSMDB-605)
=> PSMDB-605 Update psmdb-40 version

percona-server-mongodb.36/Dockerfile.k8s, percona-server-mongodb.40/Dockerfile.k8s, percona-server-mongodb.42/Dockerfile.k8s, proxysql/Dockerfile.k8s, pxc-57-backup/Dockerfile, pxc-57/Dockerfile.k8s, pxc-80-backup/Dockerfile, pxc-80/Dockerfile.k8s
[![K8SPXC-323](https://badgen.net/badge/JIRA/K8SPXC-323/green)](https://jira.percona.com/browse/K8SPXC-323)
=> K8SPXC-323 Install tar to fix 'kubectl cp' command

proxysql/dockerdir/entrypoint.sh, proxysql/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-252](https://badgen.net/badge/JIRA/K8SPXC-252/green)](https://jira.percona.com/browse/K8SPXC-252)
=> K8SPXC-252 add operator user

pxc-80-backup/run_backup.sh
[![K8SPXC-242](https://badgen.net/badge/JIRA/K8SPXC-242/green)](https://jira.percona.com/browse/K8SPXC-242)
=> K8SPXC-242 Catch the errors during the second socat call

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/etc/haproxy/haproxy.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh
=> K8SPXC-294 Add round robin for replica nodes

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
=> K8SPXC-294 Remove proxy port from replica nodes

percona-server-mongodb.42/Dockerfile, percona-server-mongodb.42/Dockerfile.debug
[![PSMDB-653](https://badgen.net/badge/JIRA/PSMDB-653/green)](https://jira.percona.com/browse/PSMDB-653)
=> PSMDB-653 create separte debug PSMDB42 docker image

percona-server-mongodb.36/Dockerfile, percona-server-mongodb.36/Dockerfile.debug, percona-server-mongodb.40/Dockerfile, percona-server-mongodb.40/Dockerfile.debug
[![PSMDB-653](https://badgen.net/badge/JIRA/PSMDB-653/green)](https://jira.percona.com/browse/PSMDB-653)
1. Create separate debug docker image for PSMDB-40 and PSMDB-36
2. Chnage FROM tag for PSMDB-42 to more generic: 4.2.7-7 -> 4.2
=> PSMDB-653 create separte debug PSMDB 40 36 docker images

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
=> K8SPXC-294 Improve  order of writer nodes

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
=> K8SPXC-294 Fix typo

percona-server-mongodb.42/Dockerfile, percona-server-mongodb.42/Dockerfile.k8s
[![PSMDB-635](https://badgen.net/badge/JIRA/PSMDB-635/green)](https://jira.percona.com/browse/PSMDB-635)
=> PSMDB-635 Update psmdb-4.2 version

haproxy/Dockerfile, haproxy/LICENSE
=> K8SPXC-294 add LICENSE for Dockerfile and  HAProxy itself

pxc-80-backup/run_backup.sh
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
=> K8SPXC-366 Do not fail the backup if socat has already finished its work

pxc-80-backup/run_backup.sh
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
=> K8SPXC-366 Set correct exit code

pxc-80-backup/run_backup.sh
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
Reverts percona/percona-docker#280
=> Revert "K8SPXC-366 Set correct exit code"

haproxy/dockerdir/entrypoint.sh, haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
* configuration file with 'default' section should be
declared as the first one
* increase the server/client default timeouts
=> K8SPXC-294 Fix default timeouts

percona-server.80/Dockerfile
[![PS-7164](https://badgen.net/badge/JIRA/PS-7164/green)](https://jira.percona.com/browse/PS-7164)
=> PS-7164 Update version

pxc-57/Dockerfile, pxc-57/Dockerfile.k8s, pxc-57/dockerdir/usr/local/bin/mysqld-debug, pxc-80/Dockerfile, pxc-80/Dockerfile.k8s, pxc-80/dockerdir/usr/local/bin/mysqld-debug
[![K8SPXC-384](https://badgen.net/badge/JIRA/K8SPXC-384/green)](https://jira.percona.com/browse/K8SPXC-384)
=> K8SPXC-384 Fix debug images for pxc operator

percona-server.56/Dockerfile, percona-server.56/Dockerfile-dockerhub
[![PS-7198](https://badgen.net/badge/JIRA/PS-7198/green)](https://jira.percona.com/browse/PS-7198)
=> PS-7198: Update percona-server.56 version

percona-distribution-postgresql.11/Dockerfile, percona-distribution-postgresql.11/LICENSE, percona-distribution-postgresql.11/README-build.md, percona-distribution-postgresql.11/README.md, percona-distribution-postgresql.11/entrypoint.sh, percona-distribution-postgresql.12/Dockerfile, percona-distribution-postgresql.12/LICENSE, percona-distribution-postgresql.12/README-build.md, percona-distribution-postgresql.12/README.md, percona-distribution-postgresql.12/entrypoint.sh, test/config.sh, test/tests/postgres-basics/run.sh, test/tests/postgres-initdb/initdb.sql, test/tests/postgres-initdb/run.sh
[![PG-119](https://badgen.net/badge/JIRA/PG-119/green)](https://jira.percona.com/browse/PG-119)
=> PG-119: Create PPG 11 & 12 images

haproxy/Dockerfile
[![K8SPXC-387](https://badgen.net/badge/JIRA/K8SPXC-387/green)](https://jira.percona.com/browse/K8SPXC-387)
=> K8SPXC-387 Adding missing labels for RedHat

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![PSQLADM-257](https://badgen.net/badge/JIRA/PSQLADM-257/green)](https://jira.percona.com/browse/PSQLADM-257)
=> PSQLADM-257 Update proxysql2 version to 2.0.13

haproxy/Dockerfile, haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-375](https://badgen.net/badge/JIRA/K8SPXC-375/green)](https://jira.percona.com/browse/K8SPXC-375)
* terminate sessions from backups pxc nodes when main pxc writer is up and
ready
=> K8SPXC-375 Terminate sessions from backup nodes

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-375](https://badgen.net/badge/JIRA/K8SPXC-375/green)](https://jira.percona.com/browse/K8SPXC-375)
=> K8SPXC-375 Add possibility of using custom 'socket'

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-625](https://badgen.net/badge/JIRA/PSMDB-625/green)](https://jira.percona.com/browse/PSMDB-625)
=> PSMDB-625 Update psmdb-3.6 version

haproxy/Dockerfile, haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/etc/haproxy/haproxy.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 Add support of proxy protocol

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-7239](https://badgen.net/badge/JIRA/PS-7239/green)](https://jira.percona.com/browse/PS-7239)
=> PS-7239: Update to 5.7.31-34

haproxy/Dockerfile, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 fix minor bugs

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/etc/haproxy/haproxy.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh, proxysql/dockerdir/entrypoint.sh
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 add support of admin port

percona-xtrabackup-8.0/Dockerfile
[![PXB-2265](https://badgen.net/badge/JIRA/PXB-2265/green)](https://jira.percona.com/browse/PXB-2265)
=> PXB-2265: Update PXB-8.0 version

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 fix missprint

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-649](https://badgen.net/badge/JIRA/PSMDB-649/green)](https://jira.percona.com/browse/PSMDB-649)
=> PSMDB-649 update psmdb4.0 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-659](https://badgen.net/badge/JIRA/PSMDB-659/green)](https://jira.percona.com/browse/PSMDB-659)
=> PSMDB-659 Update psmdb 4.2 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/LICENSE, percona-server-mongodb-4.4/README-build.md, percona-server-mongodb-4.4/README.md, percona-server-mongodb-4.4/ps-entry.sh
[![PSMDB-686](https://badgen.net/badge/JIRA/PSMDB-686/green)](https://jira.percona.com/browse/PSMDB-686)
=> Psmdb 686 add docker image for psmdb 44

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-418](https://badgen.net/badge/JIRA/K8SPXC-418/green)](https://jira.percona.com/browse/K8SPXC-418)
=> K8SPXC-418 fix calculation of pxc nodes

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.debug, percona-server-mongodb-3.6/Dockerfile.k8s
```
* CentOS 8
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
percona/percona-server-mongodb          3.6                 2d092787da88        19 seconds ago      410MB
percona/percona-server-mongodb-debug    latest              984dc38219f4        40 seconds ago     2.26GB
percona/percona-server-mongodb-k8s      latest              d13380c51757        8 seconds ago       322MB
* CentOS 7
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
percona/percona-server-mongodb         3.6                 9fd84aa75350        25 seconds ago      432MB
percona/percona-server-mongodb-debug …
```
=> ENG-878: PSMDB3.6: Update to CentOS 8

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.debug, percona-server-mongodb-4.0/Dockerfile.k8s
CentOS 8:
```
REPOSITORY                              TAG                 IMAGE ID            CREATED              SIZE
percona/percona-server-mongodb          4.0                 bb6e6752b031        About a minute ago   418MB
percona/percona-server-mongodb-debug    latest              a11950606607        21 seconds ago       2.31GB
percona/percona-server-mongodb-k8s      latest              3778d9bf1253        8 minutes ago        330MB
```
CentOS 7
```
REPOSITORY                              TAG                 IMAGE ID            CREATED              SIZE
percona/percona-server-mongodb          4.0                 2e885d636fcc        24 seconds ago      440MB …
```
=> ENG-878: PSMDB4.0: Update to CentOS 8

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.debug, percona-server-mongodb-4.2/Dockerfile.k8s
CentOS 8:
```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
percona/percona-server-mongodb         4.2                 9e23b134efbf        3 hours ago         430MB
percona/percona-server-mongodb-debug   latest              70d694ab10a6        2 minutes ago       4.95GB
percona/percona-server-mongodb-k8s     latest              017f619016bf        2 minutes ago       342MB
```
CentOS 7:
```
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
percona/percona-server-mongodb          4.2                 0350c5fc7cbe        36 seconds ago      453MB
percona/percona-server-mongodb-debug …
```
=> ENG-878: PSMDB4.2: Update to CentOS 8

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-370](https://badgen.net/badge/JIRA/K8SPXC-370/green)](https://jira.percona.com/browse/K8SPXC-370)
=> K8SPXC-438 add possibility to use 32 symbols for cluster name

proxysql/Dockerfile, proxysql/Dockerfile.k8s
CentOS 8:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
percona/percona-proxysql-k8s                  latest              a16d99473908        2 minutes ago       382MB
percona/percona-proxysql                      latest              139816e67148        5 minutes ago       469MB
```
CentOS 7:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED              SIZE
percona/percona-proxysql                      latest              36f8acdc8b31        29 seconds ago       508MB
percona/percona-proxysql-k8s                  latest              11237cf80009        About a minute ago …
```
=> ENG-878: ProxySQL: Update to CentOS 8

percona-xtrabackup-2.4/Dockerfile
CentOS 8:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
percona/percona-xtrabackup                    2.4                 16381aabb636        3 minutes ago       371MB
```
CentOS 7: 
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
percona/percona-xtrabackup   2.4                 ff802cff6f33        2 minutes ago       336MB
````
=> ENG-878: PXB2.4: Update to CentOS 8

percona-server-8.0/Dockerfile
CentOS 8:
```
REPOSITORY               TAG                 IMAGE ID            CREATED              SIZE
percona/percona-server   8.0                 df6f43cf1986        2 seconds ago       737MB
```
CentOS 7:
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
percona/percona-server   8.0                 0843c608e843        2 seconds ago       748MB
```
=> ENG-878: PS8.0: Update to CentOS 8

percona-xtrabackup-8.0/Dockerfile
CentOS 8:
```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
percona/percona-xtrabackup   8.0                 592173d4ebc8        42 seconds ago      400MB
```
CentOS 7:
```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
percona/percona-xtrabackup   8.0                 125961f26cce        About a minute ago   364MB
````
=> ENG-878: PXB8.0: Update to CentOS 8

haproxy/dockerdir/usr/local/bin/readiness-check.sh
[![K8SPXC-462](https://badgen.net/badge/JIRA/K8SPXC-462/green)](https://jira.percona.com/browse/K8SPXC-462)
=> K8SPXC-462 add readiness probe for HAproxy

haproxy/dockerdir/usr/local/bin/readiness-check.sh
[![K8SPXC-462](https://badgen.net/badge/JIRA/K8SPXC-462/green)](https://jira.percona.com/browse/K8SPXC-462)
=> K8SPXC-462 improve readiness-check script

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-689](https://badgen.net/badge/JIRA/PSMDB-689/green)](https://jira.percona.com/browse/PSMDB-689)
=> PSMDB-689 update psmdb44 version

proxysql/dockerdir/entrypoint.sh, proxysql/dockerdir/etc/proxysql/proxysql.cnf
* use static 'ECDHE-RSA-AES128-GCM-SHA256' cipher for proxysql
=> ENG-878 start to use static 'ECDHE-RSA-AES128-GCM-SHA256' cipher

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
CentOS 8:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED              SIZE
percona/percona-xtradb-cluster                8.0                 2565218bcfae        27 minutes ago       538MB
percona/percona-xtradb-cluster-k8s            latest              b161a4f50fe2        4 minutes ago        436MB
percona/percona-xtradb-cluster-backup         latest              ddd3c5e073c5        55 seconds ago       337MB
```
CentOS 7:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
percona/percona-xtradb-cluster                8.0                 c40b0f35d28e        6 minutes ago …
```
=> ENG-878: PXC8.0: Update to CentOS 8

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
CentOS 8:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED              SIZE
percona/percona-xtradb-cluster                5.7                 99e7e8f2e90d        About a minute ago   439MB
percona/percona-xtradb-cluster-k8s            latest              d97e3b958115        2 minutes ago        336MB
percona/percona-xtradb-cluster-backup         latest              f1630877f3d3        23 seconds ago       311MB
```
CentOS 7:
```
REPOSITORY                                    TAG                 IMAGE ID            CREATED              SIZE
percona/percona-xtradb-cluster                5.7                 2b36d1e9c576        About a minute ago …
```
=> ENG-878: PXC5.7: Update to CentOS 8

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-5.7/dockerdir/usr/local/bin/mysqld-debug, percona-xtradb-cluster-8.0/Dockerfile.k8s, percona-xtradb-cluster-8.0/dockerdir/usr/local/bin/mysqld-debug
[![K8SPXC-481](https://badgen.net/badge/JIRA/K8SPXC-481/green)](https://jira.percona.com/browse/K8SPXC-481)
=> K8SPXC-481 fix pxc debug images

percona-distribution-postgresql-12/Dockerfile
[![PPG-12](https://badgen.net/badge/JIRA/PPG-12/green)](https://jira.percona.com/browse/PPG-12)
=> Update PPG-12 to 12.4

percona-distribution-postgresql-11/Dockerfile
[![PPG-11](https://badgen.net/badge/JIRA/PPG-11/green)](https://jira.percona.com/browse/PPG-11)
=> Update PPG-11 to 11.9

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh, haproxy/dockerdir/usr/local/bin/readiness-check.sh
[![K8SPXC-480](https://badgen.net/badge/JIRA/K8SPXC-480/green)](https://jira.percona.com/browse/K8SPXC-480)
=> K8SPXC-480 use '33062' port when proxy protocol is enabled

percona-toolkit/Dockerfile
[![PT-1896](https://badgen.net/badge/JIRA/PT-1896/green)](https://jira.percona.com/browse/PT-1896)
```
Successfully built 5e63ea5b5e48
Successfully tagged percona/pt:latest
sudokamikaze at Sudokamikazes-Work-MacBook-Pro in ~/Git/percona-docker/percona-toolkit (master●)
$ docker run --rm -it percona/pt:latest /bin/bash
bash-4.4$ pt-mysql-summary
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
2020_10_07_07_36_49 Cannot connect to MySQL.  Check that MySQL is running and that the options after -- are correct.
bash-4.4$ exit
exit
```
=> PT-1896: Add MySQL client for PT

percona-toolkit/Dockerfile
[![PT-1896](https://badgen.net/badge/JIRA/PT-1896/green)](https://jira.percona.com/browse/PT-1896)
=> PT-1896 update to 3.2.1

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![RM-805](https://badgen.net/badge/JIRA/RM-805/green)](https://jira.percona.com/browse/RM-805)
=> RM-805 Update docker psmdb-3.6

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![RM-812](https://badgen.net/badge/JIRA/RM-812/green)](https://jira.percona.com/browse/RM-812)
=> RM-812 update psmdb-4.0

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![RM-813](https://badgen.net/badge/JIRA/RM-813/green)](https://jira.percona.com/browse/RM-813)
=> RM-813 Update psmdb-42

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![RM-826](https://badgen.net/badge/JIRA/RM-826/green)](https://jira.percona.com/browse/RM-826)
=> RM-826 Update psmdb-4.4

percona-server-mongodb-3.6/Dockerfile.debug, percona-server-mongodb-3.6/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.debug, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.debug, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![ENG-927](https://badgen.net/badge/JIRA/ENG-927/green)](https://jira.percona.com/browse/ENG-927)
=> ENG-927: Misc fixes

haproxy/dockerdir/entrypoint.sh, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-487](https://badgen.net/badge/JIRA/K8SPXC-487/green)](https://jira.percona.com/browse/K8SPXC-487)
* reload HAproxy via socket
=> K8SPXC-487 Improve HAproxy reload

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-424](https://badgen.net/badge/JIRA/K8SPXC-424/green)](https://jira.percona.com/browse/K8SPXC-424)
=> K8SPXC-424 Improve logging of 'check_pxc.sh' script

percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-13/LICENSE, percona-distribution-postgresql-13/README-build.md, percona-distribution-postgresql-13/README.md, percona-distribution-postgresql-13/entrypoint.sh
[![DISTPG-133](https://badgen.net/badge/JIRA/DISTPG-133/green)](https://jira.percona.com/browse/DISTPG-133)
=> DISTPG-133 Create docker for ppg-13

percona-server-mongodb-3.6/Dockerfile.debug, percona-server-mongodb-3.6/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.debug, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.debug, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s
[![K8SPSMDB-281](https://badgen.net/badge/JIRA/K8SPSMDB-281/green)](https://jira.percona.com/browse/K8SPSMDB-281)
=> K8SPSMDB-28 fix psmdb debug images part 2

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-5.7-backup/recovery-s3.sh
[![K8SPXC-491](https://badgen.net/badge/JIRA/K8SPXC-491/green)](https://jira.percona.com/browse/K8SPXC-491)
=> K8SPXC-491 fix XtraBackup compression for PXC 5.7

percona-xtradb-cluster-5.6/Dockerfile
[![PXC-3392](https://badgen.net/badge/JIRA/PXC-3392/green)](https://jira.percona.com/browse/PXC-3392)
=> PXC-3392 Update pxc 5.6 version(cve update)

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-732](https://badgen.net/badge/JIRA/PSMDB-732/green)](https://jira.percona.com/browse/PSMDB-732)
=> PSMDB-732 Update psmdb-36 version

fluentbit/Dockerfile, fluentbit/LICENSE, fluentbit/dockerdir/entrypoint.sh, fluentbit/dockerdir/etc/fluentbit/fluentbit.conf, fluentbit/dockerdir/etc/fluentbit/fluentbit_pxc.conf
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485)
=> K8SPXC-485 add fluentbit docker image

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-734](https://badgen.net/badge/JIRA/PSMDB-734/green)](https://jira.percona.com/browse/PSMDB-734)
=> PSMDB-734 update psmdb-42 version

percona-server-5.6/Dockerfile, percona-server-5.6/Dockerfile-dockerhub
[![PS-7398](https://badgen.net/badge/JIRA/PS-7398/green)](https://jira.percona.com/browse/PS-7398)
Images has been pushed
=> PS-7398: Update PS-5.6 version

fluentbit/dockerdir/entrypoint.sh, fluentbit/dockerdir/etc/fluentbit/fluentbit.conf, fluentbit/dockerdir/etc/fluentbit/fluentbit_pxc.conf
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485)
coping can be an issue if security settings force readonly docker
filesystem.
=> K8SPXC-485 avoid unnesesary coping

percona-distribution-postgresql-11/Dockerfile, percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-13/Dockerfile, percona-server-5.7/Dockerfile, percona-server-8.0/Dockerfile, percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.4/Dockerfile, percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, proxysql/Dockerfile
[![ENG-931](https://badgen.net/badge/JIRA/ENG-931/green)](https://jira.percona.com/browse/ENG-931)
=> ENG-931: Remove conflicting labels

percona-server-5.7/Dockerfile, percona-server-8.0/Dockerfile, percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.4/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, proxysql/Dockerfile
[![ENG-931](https://badgen.net/badge/JIRA/ENG-931/green)](https://jira.percona.com/browse/ENG-931)
Requestd by Tianon from Docker-official
=> ENG-931: Move versions block little lower and guard codeblocks with set -ex

fluentbit/Dockerfile, fluentbit/dockerdir/entrypoint.sh, fluentbit/dockerdir/opt/percona/logrotate/logrotate-mysql.conf, fluentbit/dockerdir/usr/local/bin/postrotate-mysql.sh
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485)
=> K8SPXC-485 add logrotation

percona-server-mongodb-3.6/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.k8s
[![K8SPSMDB-313](https://badgen.net/badge/JIRA/K8SPSMDB-313/green)](https://jira.percona.com/browse/K8SPSMDB-313)
=> K8SPSMDB-313 Old description labels

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-733](https://badgen.net/badge/JIRA/PSMDB-733/green)](https://jira.percona.com/browse/PSMDB-733)
=> PSMDB-733 update psmdb-40 version

percona-server-5.7/Dockerfile
[![PS-7422](https://badgen.net/badge/JIRA/PS-7422/green)](https://jira.percona.com/browse/PS-7422)
=> PS-7422: Update PS-5.7 image to 5.7.32-35.1

percona-server-5.7/Dockerfile-dockerhub
[![PS-7440](https://badgen.net/badge/JIRA/PS-7440/green)](https://jira.percona.com/browse/PS-7440)
=> PS-7440 Fix UUID

percona-server-5.7/Dockerfile-dockerhub
[![PS-7440](https://badgen.net/badge/JIRA/PS-7440/green)](https://jira.percona.com/browse/PS-7440)
=> PS-7440 Add set -ex

fluentbit/dockerdir/usr/local/bin/postrotate-mysql.sh
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485)
=> K8SPXC-485 flush error log only

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-747](https://badgen.net/badge/JIRA/PSMDB-747/green)](https://jira.percona.com/browse/PSMDB-747)
=> PSMDB-747 update psmdb-36 version

percona-server-mongodb-3.6/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.k8s, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, proxysql/Dockerfile.k8s
[![CLOUD-600](https://badgen.net/badge/JIRA/CLOUD-600/green)](https://jira.percona.com/browse/CLOUD-600)
=> CLOUD-600 update rpms version

percona-server-8.0/Dockerfile
[![PS-7454](https://badgen.net/badge/JIRA/PS-7454/green)](https://jira.percona.com/browse/PS-7454)
=> PS-7454 Ipdate version

proxysql/dockerdir/entrypoint.sh, proxysql/dockerdir/etc/proxysql-admin.cnf
[![K8SPXC-553](https://badgen.net/badge/JIRA/K8SPXC-553/green)](https://jira.percona.com/browse/K8SPXC-553)
=> K8SPXC-553 improve the way how to modify configuration file

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile
[![K8SPXC-530](https://badgen.net/badge/JIRA/K8SPXC-530/green)](https://jira.percona.com/browse/K8SPXC-530)
=> K8SPXC-530 Added pitr binary

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile
[![K8SPXC-530](https://badgen.net/badge/JIRA/K8SPXC-530/green)](https://jira.percona.com/browse/K8SPXC-530)
=> K8SPXC-530 Fix peer-list build

percona-xtradb-cluster-5.7-backup/get-pxc-state, percona-xtradb-cluster-8.0-backup/get-pxc-state
[![K8SPXC-530](https://badgen.net/badge/JIRA/K8SPXC-530/green)](https://jira.percona.com/browse/K8SPXC-530)
=> K8SPXC-530 Update get-pxc-state

haproxy/dockerdir/entrypoint.sh, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-543](https://badgen.net/badge/JIRA/K8SPXC-543/green)](https://jira.percona.com/browse/K8SPXC-543)
=> K8SPXC-543 add validation of custom config for haproxy

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-763](https://badgen.net/badge/JIRA/PSMDB-763/green)](https://jira.percona.com/browse/PSMDB-763)
=> PSMDB-763 update psmdb-42 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-735](https://badgen.net/badge/JIRA/PSMDB-735/green)](https://jira.percona.com/browse/PSMDB-735)
=> PSMDB-735 update psmdb-4.4 version

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh, haproxy/dockerdir/usr/local/bin/readiness-check.sh
[![K8SPXC-552](https://badgen.net/badge/JIRA/K8SPXC-552/green)](https://jira.percona.com/browse/K8SPXC-552)
=> K8SPXC-552 Set monitor user pass from file

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-778](https://badgen.net/badge/JIRA/PSMDB-778/green)](https://jira.percona.com/browse/PSMDB-778)
=> PSMDB-778 update psmdb-36 version

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-768](https://badgen.net/badge/JIRA/PSMDB-768/green)](https://jira.percona.com/browse/PSMDB-768)
=> PSMDB-768 update psmdb-40 version

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile
[![K8SPXC-570](https://badgen.net/badge/JIRA/K8SPXC-570/green)](https://jira.percona.com/browse/K8SPXC-570)
=> K8SPXC-570 update 'mc' to RELEASE.2020-12-18T10-53-53Z

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/get-pxc-state
[![K8SPXC-582](https://badgen.net/badge/JIRA/K8SPXC-582/green)](https://jira.percona.com/browse/K8SPXC-582) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-582 Add pass from file to get-pxc-state

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-589](https://badgen.net/badge/JIRA/K8SPXC-589/green)](https://jira.percona.com/browse/K8SPXC-589) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-589 improve detection of the correct backup state

percona-distribution-postgresql-11/Dockerfile, percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-13/Dockerfile
[![DISTPG-164](https://badgen.net/badge/JIRA/DISTPG-164/green)](https://jira.percona.com/browse/DISTPG-164) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTPG-164 Update dockers

haproxy/dockerdir/entrypoint.sh
[![K8SPXC-544](https://badgen.net/badge/JIRA/K8SPXC-544/green)](https://jira.percona.com/browse/K8SPXC-544) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-544 do not overwrite conf file if it already exists

proxysql/Dockerfile.k8s
[![K8SPXC-541](https://badgen.net/badge/JIRA/K8SPXC-541/green)](https://jira.percona.com/browse/K8SPXC-541) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-541 use proxysql ver 2.0.12

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile
[![K8SPXC-570](https://badgen.net/badge/JIRA/K8SPXC-570/green)](https://jira.percona.com/browse/K8SPXC-570) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-570 update 'mc' to RELEASE.2021-01-05T05-03-58Z

percona-xtradb-cluster-5.7/dockerdir/etc/mysql/node.cnf, percona-xtradb-cluster-8.0/dockerdir/etc/mysql/node.cnf
[![K8SPXC-607](https://badgen.net/badge/JIRA/K8SPXC-607/green)](https://jira.percona.com/browse/K8SPXC-607) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-607 enable libcoredumper for PXCO

proxysql/Dockerfile.k8s
[![K8SPXC-541](https://badgen.net/badge/JIRA/K8SPXC-541/green)](https://jira.percona.com/browse/K8SPXC-541) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-541  revert 87a5a95 commit

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-798](https://badgen.net/badge/JIRA/PSMDB-798/green)](https://jira.percona.com/browse/PSMDB-798) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-798 Update psmdb-40 version

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-5.7-backup/get-pxc-state, percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/get-pxc-state
[![K8SPXC-571](https://badgen.net/badge/JIRA/K8SPXC-571/green)](https://jira.percona.com/browse/K8SPXC-571) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-571 do not allow using pxc nodes as donors for backups

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-780](https://badgen.net/badge/JIRA/PSMDB-780/green)](https://jira.percona.com/browse/PSMDB-780) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-780 Update psmdb-44 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-779](https://badgen.net/badge/JIRA/PSMDB-779/green)](https://jira.percona.com/browse/PSMDB-779) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-779 update psmdb-42 version

percona-server-5.6/Dockerfile, percona-server-5.6/Dockerfile-dockerhub
[![PS-7541](https://badgen.net/badge/JIRA/PS-7541/green)](https://jira.percona.com/browse/PS-7541) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7541 update ps-56 version

fluentbit/dockerdir/etc/fluentbit/fluentbit_pxc.conf
[![K8SPXC-638](https://badgen.net/badge/JIRA/K8SPXC-638/green)](https://jira.percona.com/browse/K8SPXC-638) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-638 fix delay in showing logs

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-535](https://badgen.net/badge/JIRA/K8SPXC-535/green)](https://jira.percona.com/browse/K8SPXC-535) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-535 add useful tools to pxc debug image

percona-xtradb-cluster-5.6/Dockerfile
[![PXC-3517](https://badgen.net/badge/JIRA/PXC-3517/green)](https://jira.percona.com/browse/PXC-3517) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3517 update pxc-56 version

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-819](https://badgen.net/badge/JIRA/PSMDB-819/green)](https://jira.percona.com/browse/PSMDB-819) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-819 update psmdb-36 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-825](https://badgen.net/badge/JIRA/PSMDB-825/green)](https://jira.percona.com/browse/PSMDB-825) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-825 update psmdb-44 version

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-7579](https://badgen.net/badge/JIRA/PS-7579/green)](https://jira.percona.com/browse/PS-7579) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7579 Update ps-57 version

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-833](https://badgen.net/badge/JIRA/PSMDB-833/green)](https://jira.percona.com/browse/PSMDB-833) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-833 Update psmdb-40 version

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-618](https://badgen.net/badge/JIRA/K8SPXC-618/green)](https://jira.percona.com/browse/K8SPXC-618) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-618 add percona-xtradb-cluster-server-debuginfo to debug image

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![K8SPXC-618](https://badgen.net/badge/JIRA/K8SPXC-618/green)](https://jira.percona.com/browse/K8SPXC-618) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-618 install pxc57 server debuginfo

CONTRIBUTING.md, README.md, code-of-conduct.md
[![CLOUD-618](https://badgen.net/badge/JIRA/CLOUD-618/green)](https://jira.percona.com/browse/CLOUD-618) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-618 add contributing guide to docker images

percona-xtradb-cluster-5.6/Dockerfile
[![PXC-3603](https://badgen.net/badge/JIRA/PXC-3603/green)](https://jira.percona.com/browse/PXC-3603) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3603 update pxc-56 version

percona-server-mongodb-3.6/Dockerfile, percona-server-mongodb-3.6/Dockerfile.k8s
[![PSMDB-846](https://badgen.net/badge/JIRA/PSMDB-846/green)](https://jira.percona.com/browse/PSMDB-846) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-846 Update psmdb-36 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-848](https://badgen.net/badge/JIRA/PSMDB-848/green)](https://jira.percona.com/browse/PSMDB-848) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-848 update psmdb-42 version

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-43](https://badgen.net/badge/JIRA/K8SPG-43/green)](https://jira.percona.com/browse/K8SPG-43) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-43 add possibility of building different versions of PG images

haproxy/Dockerfile, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-688](https://badgen.net/badge/JIRA/K8SPXC-688/green)](https://jira.percona.com/browse/K8SPXC-688) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-688 add possibility of customising HAProxy configuration

postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-45](https://badgen.net/badge/JIRA/K8SPG-45/green)](https://jira.percona.com/browse/K8SPG-45) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-45 add dependency for a new version of patroni

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-856](https://badgen.net/badge/JIRA/PSMDB-856/green)](https://jira.percona.com/browse/PSMDB-856) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-856 update psmdb-44 version

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-48](https://badgen.net/badge/JIRA/K8SPG-48/green)](https://jira.percona.com/browse/K8SPG-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-48 use ppg release repos

percona-server-8.0/Dockerfile
[![PS-7660](https://badgen.net/badge/JIRA/PS-7660/green)](https://jira.percona.com/browse/PS-7660) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7660 update ps-80 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-867](https://badgen.net/badge/JIRA/PSMDB-867/green)](https://jira.percona.com/browse/PSMDB-867) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-867 update psmdb-42 version

fluentbit/Dockerfile, haproxy/Dockerfile
[![K8SPXC-746](https://badgen.net/badge/JIRA/K8SPXC-746/green)](https://jira.percona.com/browse/K8SPXC-746) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-746 add 'vim-minimal' package

percona-xtradb-cluster-8.0-backup/get-pxc-state
[![K8SPXC-743](https://badgen.net/badge/JIRA/K8SPXC-743/green)](https://jira.percona.com/browse/K8SPXC-743) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-743 remove confusing error messages from the log of backup

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/recovery-pvc-joiner.sh
[![K8SPXC-742](https://badgen.net/badge/JIRA/K8SPXC-742/green)](https://jira.percona.com/browse/K8SPXC-742) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* we can update socat for backup images separately from pxc
image without any issues
* for now we can't update it for pxc images because additional
changes from pxc side are required
=> K8SPXC-742 update socat version to 1.7.4

percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.k8s
[![CLOUD-627](https://badgen.net/badge/JIRA/CLOUD-627/green)](https://jira.percona.com/browse/CLOUD-627) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-627 fix build of mongodb docker images

percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.k8s, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![CLOUD-627](https://badgen.net/badge/JIRA/CLOUD-627/green)](https://jira.percona.com/browse/CLOUD-627) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-627 update versions of rpms for mongodb/pxc/pxb docker images

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile
[![K8SPG-55](https://badgen.net/badge/JIRA/K8SPG-55/green)](https://jira.percona.com/browse/K8SPG-55) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* pgbackrest v2.33 was pushed to release repo
=> K8SPG-55 install the latest pgbackrest from release repo

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
[![K8SPXC-673](https://badgen.net/badge/JIRA/K8SPXC-673/green)](https://jira.percona.com/browse/K8SPXC-673) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-673: Enable haproxy metrics endpoint

percona-xtradb-cluster-5.7-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/recovery-pvc-joiner.sh
[![K8SPXC-742](https://badgen.net/badge/JIRA/K8SPXC-742/green)](https://jira.percona.com/browse/K8SPXC-742) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* 'no-sni' can be used only with certificates
=> K8SPXC-742 fix missprint

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s
[![PSMDB-881](https://badgen.net/badge/JIRA/PSMDB-881/green)](https://jira.percona.com/browse/PSMDB-881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-881 update psmdb-40 version

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-7719](https://badgen.net/badge/JIRA/PS-7719/green)](https://jira.percona.com/browse/PS-7719) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7719 update ps-57 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s
[![PSMDB-870](https://badgen.net/badge/JIRA/PSMDB-870/green)](https://jira.percona.com/browse/PSMDB-870) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-870 update psmdb-44 version

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-785](https://badgen.net/badge/JIRA/K8SPXC-785/green)](https://jira.percona.com/browse/K8SPXC-785) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* when we perform the backup we check whether this backup already
exists or not in the bucket and if it exists we delete it
to have the possibility of rewriting it
=> K8SPXC-785 avoid error message

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/etc/haproxy/haproxy.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-421](https://badgen.net/badge/JIRA/K8SPXC-421/green)](https://jira.percona.com/browse/K8SPXC-421) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-421: Enable X protocol in HAProxy

postgresql-containers/bin/postgres-ha/bootstrap-postgres-ha.sh, postgresql-containers/bin/postgres-ha/bootstrap/post-bootstrap.sh, postgresql-containers/bin/postgres-ha/bootstrap/pre-bootstrap.sh, postgresql-containers/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
[![K8SPG-82](https://badgen.net/badge/JIRA/K8SPG-82/green)](https://jira.percona.com/browse/K8SPG-82) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-82 fix restores from S3 bucket 

percona-server-8.0/Dockerfile
[![PS-7726](https://badgen.net/badge/JIRA/PS-7726/green)](https://jira.percona.com/browse/PS-7726) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7726 update ps-8.0.25 version

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-3708](https://badgen.net/badge/JIRA/PXC-3708/green)](https://jira.percona.com/browse/PXC-3708) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3708 update socat for pxc57 docker image

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-821](https://badgen.net/badge/JIRA/K8SPXC-821/green)](https://jira.percona.com/browse/K8SPXC-821) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-821
Add --reload flag to ProxySQL container to be able to update configuration after pod restart
=> K8SPXC-821 feature: add --reload flag to ProxySQL

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s
[![PSMDB-895](https://badgen.net/badge/JIRA/PSMDB-895/green)](https://jira.percona.com/browse/PSMDB-895) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-895 Update psmdb-42 version

haproxy/dockerdir/usr/local/bin/check_pxc.sh, haproxy/dockerdir/usr/local/bin/liveness-check.sh
[![K8SPXC-749](https://badgen.net/badge/JIRA/K8SPXC-749/green)](https://jira.percona.com/browse/K8SPXC-749) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-749 use values for timeouts from liveness/readiness probs

percona-server-mongodb-4.4/Dockerfile.k8s
[![K8SPSMDB-515](https://badgen.net/badge/JIRA/K8SPSMDB-515/green)](https://jira.percona.com/browse/K8SPSMDB-515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Fetch dependency js-yaml for PSMDB operator

haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-688](https://badgen.net/badge/JIRA/K8SPXC-688/green)](https://jira.percona.com/browse/K8SPXC-688) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-688 check if files exist

fluentbit/dockerdir/entrypoint.sh
[![K8SPXC-794](https://badgen.net/badge/JIRA/K8SPXC-794/green)](https://jira.percona.com/browse/K8SPXC-794) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-794
=> K8SPXC-794 remove verbose flag

fluentbit/Dockerfile, fluentbit/dockerdir/entrypoint.sh, fluentbit/dockerdir/opt/percona/logrotate/logrotate-mysql.conf
[![K8SPXC-822](https://badgen.net/badge/JIRA/K8SPXC-822/green)](https://jira.percona.com/browse/K8SPXC-822) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-822
=> K8SPXC-822 do not rotate GRA logs

fluentbit/Dockerfile, fluentbit/dockerdir/etc/fluentbit/fluentbit_pxc.conf, fluentbit/dockerdir/etc/fluentbit/parsers_multiline.conf
[![K8SPXC-793](https://badgen.net/badge/JIRA/K8SPXC-793/green)](https://jira.percona.com/browse/K8SPXC-793) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* update fluentbit to the latest version
=> K8SPXC-793 add multiline parsing

percona-server-mongodb-3.4/ps-entry.sh, percona-server-mongodb-3.6/ps-entry.sh, percona-server-mongodb-4.0/ps-entry.sh, percona-server-mongodb-4.2/ps-entry.sh, percona-server-mongodb-4.4/ps-entry.sh
I got the error that there is  "find: '/data/configdb': no such file or directory" when running as kubernetes containers.
=> fix bug when /data/configdb or /data/db not exist

percona-server-mongodb-5.0/ps-entry.sh
[![PSMDB-7](https://badgen.net/badge/JIRA/PSMDB-7/green)](https://jira.percona.com/browse/PSMDB-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Cherry-pick changes
from https://github.com/percona/percona-docker/pull/472
to v5.0 branch
=> PSMDB-7 check folders existance one by one

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-38](https://badgen.net/badge/JIRA/K8SPG-38/green)](https://jira.percona.com/browse/K8SPG-38) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Preious verions is need to overcome Openshift security restrictions.
=> K8SPG-38 Use 2.33 backrest

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 add support of PG14

postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 fix postgres-ha

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
"Testing" is build, run, remove. Regular and debug containers were built.
=> [ENG-1065] feature: Implemented switch to UBI:8 for PXC

percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile
"Testing" is build, run, remove
=> [ENG-1065] feature: Implemented switch to UBI:8 for PXB

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub, percona-server-8.0/Dockerfile
"Testing" is build, run, remove
=> [ENG-1065] feature: Implemented switch to UBI:8 for PS

proxysql/Dockerfile, proxysql/Dockerfile.k8s
"Testing" is build, run, remove
=> [ENG-1065] feature: Implemented switch to UBI:8 for ProxySQL

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s
=> [ENG-1065] feature: Implemented switch to UBI:8 for PSMDB

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile
[![PXC-3806](https://badgen.net/badge/JIRA/PXC-3806/green)](https://jira.percona.com/browse/PXC-3806) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [PXC-3806] fix: Missing procps-ng in PXC-5.7 docker image

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-902](https://badgen.net/badge/JIRA/K8SPXC-902/green)](https://jira.percona.com/browse/K8SPXC-902) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-902 fix overwriting of the admin port

haproxy/Dockerfile
[![K8SPXC-903](https://badgen.net/badge/JIRA/K8SPXC-903/green)](https://jira.percona.com/browse/K8SPXC-903) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-903 change USER to numeric

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-906](https://badgen.net/badge/JIRA/K8SPXC-906/green)](https://jira.percona.com/browse/K8SPXC-906) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-906 downgrade socat for PXC 8.0.23-14.1

percona-xtradb-cluster-5.7-backup/get-pxc-state, percona-xtradb-cluster-8.0-backup/get-pxc-state
[![K8SPXC-904](https://badgen.net/badge/JIRA/K8SPXC-904/green)](https://jira.percona.com/browse/K8SPXC-904) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-904 use admin port in get-pxc-state

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 start to use experimental repo

orchestrator/Dockerfile, orchestrator/dockerdir/usr/bin/add_mysql_nodes.sh
[![K8SPS-13](https://badgen.net/badge/JIRA/K8SPS-13/green)](https://jira.percona.com/browse/K8SPS-13) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-13 add check of mysql availability

postgresql-containers/build/pgbadger/Dockerfile
=> K8SPG-77 fix pgbadger docker image

percona-backup-mongodb/Dockerfile
[![RM-964](https://badgen.net/badge/JIRA/RM-964/green)](https://jira.percona.com/browse/RM-964) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Updated PBM to 1.6.1

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 update packages due to Centos 8.5.2111 release

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 start to use 14.1 testing repo

percona-xtradb-cluster-5.7/Dockerfile
[![PXC-3790](https://badgen.net/badge/JIRA/PXC-3790/green)](https://jira.percona.com/browse/PXC-3790) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [PXC-3790] chore: Updated repo and package URLs

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
=> K8SPG-77 use release repo for PG14

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-7](https://badgen.net/badge/JIRA/PXC-7/green)](https://jira.percona.com/browse/PXC-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-7 update pxc-8.0 version

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile
[![K8SPG-146](https://badgen.net/badge/JIRA/K8SPG-146/green)](https://jira.percona.com/browse/K8SPG-146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-146 add 'tar' to make it possible to use 'kubectl cp'

percona-server-8.0/Dockerfile.ubi8
Official Docker Hub images should be based on other official images
=> [ENG-1065] PS80: Switching back to CentOS 8

percona-backup-mongodb/start-agent.sh
[![K8SPSMDB-608](https://badgen.net/badge/JIRA/K8SPSMDB-608/green)](https://jira.percona.com/browse/K8SPSMDB-608) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-608
=> K8SPSMDB-608 fix: password of backup user is printed in backup-agent logs

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-5.7-backup/recovery-s3.sh, percona-xtradb-cluster-8.0-backup/recovery-s3.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-758](https://badgen.net/badge/JIRA/K8SPXC-758/green)](https://jira.percona.com/browse/K8SPXC-758) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-758
Add check for `VERIFY_TLS` variable. If it's 0, add `--insecure` flag to `mc` and `xbcloud`
=> K8SPXC-758: Allow skipping TLS verification for backup storage

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-7](https://badgen.net/badge/JIRA/PS-7/green)](https://jira.percona.com/browse/PS-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7 5.7.36 release

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
=> [ENG-1065] Official Docker Hub images should be based on other official images

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![K8SPXC-929](https://badgen.net/badge/JIRA/K8SPXC-929/green)](https://jira.percona.com/browse/K8SPXC-929) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-929 - Update PXC version in cloud images to 5.7.35

fluentbit/Dockerfile, haproxy/Dockerfile, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-929](https://badgen.net/badge/JIRA/K8SPXC-929/green)](https://jira.percona.com/browse/K8SPXC-929) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-929 - Update versions in cloud images

percona-server-5.6/Dockerfile, percona-server-5.6/Dockerfile-dockerhub
[![PS-8019](https://badgen.net/badge/JIRA/PS-8019/green)](https://jira.percona.com/browse/PS-8019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8019 Update docker image

haproxy/Dockerfile, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-929](https://badgen.net/badge/JIRA/K8SPXC-929/green)](https://jira.percona.com/browse/K8SPXC-929) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-929 - Update golang to 1.17 in PXC and Cloud images

orchestrator/dockerdir/etc/orchestrator/orchestrator.conf.json
[![K8SPS-48](https://badgen.net/badge/JIRA/K8SPS-48/green)](https://jira.percona.com/browse/K8SPS-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-48: Shorten recovery block period

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.debug, percona-server-mongodb-5.0/Dockerfile.ubi8
=> [ENG-1065] Docker Official image for PSMDB 5.0

percona-server-mongodb-4.0/Dockerfile.debug, percona-server-mongodb-4.0/Dockerfile.ubi8
=> [ENG-1065] Docker Official image for PSMDB-4.0

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s
[![PSMDB-973](https://badgen.net/badge/JIRA/PSMDB-973/green)](https://jira.percona.com/browse/PSMDB-973) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-973 update psmdb-50 version

fluentbit/Dockerfile
[![K8SPXC-932](https://badgen.net/badge/JIRA/K8SPXC-932/green)](https://jira.percona.com/browse/K8SPXC-932) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* update version of fluentbit
=> K8SPXC-932 start to use ubi8 as a base image for logcollector

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-7](https://badgen.net/badge/JIRA/PS-7/green)](https://jira.percona.com/browse/PS-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7 update ps-80 version

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile
[![PG-340](https://badgen.net/badge/JIRA/PG-340/green)](https://jira.percona.com/browse/PG-340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [PG-340] Some Python packages were updated.

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.debug, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-995](https://badgen.net/badge/JIRA/PSMDB-995/green)](https://jira.percona.com/browse/PSMDB-995) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-995 update psmdb-5.0 version

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-3882](https://badgen.net/badge/JIRA/PXC-3882/green)](https://jira.percona.com/browse/PXC-3882) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3882 update pxc-57 version

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.debug, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.ubi8
[![PSMDB-998](https://badgen.net/badge/JIRA/PSMDB-998/green)](https://jira.percona.com/browse/PSMDB-998) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-998 update psmdb-40 version

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-7](https://badgen.net/badge/JIRA/PS-7/green)](https://jira.percona.com/browse/PS-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-7 Update version

percona-server-mongodb-4.0/Dockerfile.k8s
[![CLOUD-687](https://badgen.net/badge/JIRA/CLOUD-687/green)](https://jira.percona.com/browse/CLOUD-687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-687 Replace centos FQDN with working one

percona-server-mongodb-4.0/Dockerfile, percona-server-mongodb-4.0/Dockerfile.k8s, percona-server-mongodb-4.0/Dockerfile.ubi8, percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![CLOUD-688](https://badgen.net/badge/JIRA/CLOUD-688/green)](https://jira.percona.com/browse/CLOUD-688) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Fixes:
https://jira.percona.com/browse/CLOUD-688
https://jira.percona.com/browse/PSMDB-1004
=> CLOUD-688 - Fix image build for PXC 8.0 image and PSMDB k8s

postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-181](https://badgen.net/badge/JIRA/K8SPG-181/green)](https://jira.percona.com/browse/K8SPG-181) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-181 build yq using go 1.17

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/pgbouncer/Dockerfile
[![CLOUD-687](https://badgen.net/badge/JIRA/CLOUD-687/green)](https://jira.percona.com/browse/CLOUD-687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-687 Fix missing package

postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-181](https://badgen.net/badge/JIRA/K8SPG-181/green)](https://jira.percona.com/browse/K8SPG-181) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-181 update yq

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-988](https://badgen.net/badge/JIRA/PSMDB-988/green)](https://jira.percona.com/browse/PSMDB-988) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-988 update psmdb-4.4 version

fluentbit/Dockerfile, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![CLOUD-688](https://badgen.net/badge/JIRA/CLOUD-688/green)](https://jira.percona.com/browse/CLOUD-688) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Builds are failing here: https://cloud.cd.percona.com/view/PXC/job/pxc-containers-docker-build/
=> CLOUD-688 - Fix centos mirrors for PXC builds

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1012](https://badgen.net/badge/JIRA/PSMDB-1012/green)](https://jira.percona.com/browse/PSMDB-1012) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1012 update psmdb-4.4 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.debug, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1014](https://badgen.net/badge/JIRA/PSMDB-1014/green)](https://jira.percona.com/browse/PSMDB-1014) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1014 update psmdb-4.2 version

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-3915](https://badgen.net/badge/JIRA/PXC-3915/green)](https://jira.percona.com/browse/PXC-3915) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3915 add mysqlbinlog binary to pxc-80 docker image

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh, haproxy/dockerdir/usr/local/bin/check_pxc.sh, haproxy/dockerdir/usr/local/bin/liveness-check.sh, haproxy/dockerdir/usr/local/bin/readiness-check.sh
[![K8SPXC-984](https://badgen.net/badge/JIRA/K8SPXC-984/green)](https://jira.percona.com/browse/K8SPXC-984) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-984 start to use admin port by default

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-3914](https://badgen.net/badge/JIRA/PXC-3914/green)](https://jira.percona.com/browse/PXC-3914) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3914 update socat pkg in pxc docker images

percona-xtradb-cluster-5.7-backup/backup.sh
[![K8SPXC-997](https://badgen.net/badge/JIRA/K8SPXC-997/green)](https://jira.percona.com/browse/K8SPXC-997) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-997 Detection of additional garbd error

percona-xtrabackup-8.0/Dockerfile
[![K8SPS-53](https://badgen.net/badge/JIRA/K8SPS-53/green)](https://jira.percona.com/browse/K8SPS-53) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
we are going to use official PXB docker image for PS operator that is why we need to add additional  utils like socat
=> K8SPS-53: Add ps utils to xtrabackup 8.0

percona-backup-mongodb/Dockerfile
[![PBM-826](https://badgen.net/badge/JIRA/PBM-826/green)](https://jira.percona.com/browse/PBM-826) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-826 update PBM version

percona-xtrabackup-2.4/Dockerfile
[![PXB-2748](https://badgen.net/badge/JIRA/PXB-2748/green)](https://jira.percona.com/browse/PXB-2748) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2748 update pxb-2.4 version

percona-xtrabackup-8.0/Dockerfile
[![PXB-2747](https://badgen.net/badge/JIRA/PXB-2747/green)](https://jira.percona.com/browse/PXB-2747) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2747 update pxb-8.0 version

orchestrator/Dockerfile, orchestrator/dockerdir/entrypoint.sh, orchestrator/dockerdir/etc/orchestrator/orchestrator.conf.json, orchestrator/dockerdir/usr/bin/add_mysql_nodes.sh
[![K8SPS-32](https://badgen.net/badge/JIRA/K8SPS-32/green)](https://jira.percona.com/browse/K8SPS-32) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-32: Orchestrator raft setup

haproxy/Dockerfile, orchestrator/Dockerfile, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-1007](https://badgen.net/badge/JIRA/K8SPXC-1007/green)](https://jira.percona.com/browse/K8SPXC-1007) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1007 update go version to 1.18

percona-xtrabackup-2.4/Dockerfile
[![PXB-2765](https://badgen.net/badge/JIRA/PXB-2765/green)](https://jira.percona.com/browse/PXB-2765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2765 update pxb-2.4 version

percona-server-8.0/ps-entry.sh
[![PS-8210](https://badgen.net/badge/JIRA/PS-8210/green)](https://jira.percona.com/browse/PS-8210) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8210 Fix rocksdb in docker

fluentbit/Dockerfile
[![K8SPXC-982](https://badgen.net/badge/JIRA/K8SPXC-982/green)](https://jira.percona.com/browse/K8SPXC-982) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
@tplavcic we need to downgrade fluentbit to 1.8.11 due to the following issue https://github.com/fluent/fluent-bit/issues/5174
=> K8SPXC-982 downgrade fluentbit to 1.8.11

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1015](https://badgen.net/badge/JIRA/K8SPXC-1015/green)](https://jira.percona.com/browse/K8SPXC-1015) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1015 update mc to 'RELEASE.2022-05-04T06-07-55Z'

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-8203](https://badgen.net/badge/JIRA/PS-8203/green)](https://jira.percona.com/browse/PS-8203) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8203 Release tasks for PS 8.0.28-19

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-1000](https://badgen.net/badge/JIRA/K8SPXC-1000/green)](https://jira.percona.com/browse/K8SPXC-1000) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1000 improve backup messages

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1059](https://badgen.net/badge/JIRA/PSMDB-1059/green)](https://jira.percona.com/browse/PSMDB-1059) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1059 update psmdb-4.2 version

percona-xtradb-cluster-5.7-backup/backup.sh
[![K8SPXC-997](https://badgen.net/badge/JIRA/K8SPXC-997/green)](https://jira.percona.com/browse/K8SPXC-997) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This reverts commit 089651b46d012d60264af73b410e52f23394c09e.
=> Revert "K8SPXC-997 Detection of additional garbd error (#592)"

percona-xtrabackup-8.0/Dockerfile
[![PXB-2785](https://badgen.net/badge/JIRA/PXB-2785/green)](https://jira.percona.com/browse/PXB-2785) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2785 update pxb-8.0 version

orchestrator/dockerdir/etc/orchestrator/orchestrator.conf.json
[![K8SPS-41](https://badgen.net/badge/JIRA/K8SPS-41/green)](https://jira.percona.com/browse/K8SPS-41) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-41: Use super_read_only

percona-server-8.0/Dockerfile
[![PS-8272](https://badgen.net/badge/JIRA/PS-8272/green)](https://jira.percona.com/browse/PS-8272) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8272 PS 8.0 docker: install "hostname" utility

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1079](https://badgen.net/badge/JIRA/PSMDB-1079/green)](https://jira.percona.com/browse/PSMDB-1079) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1079 update psmdb-5.0 version

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-8286](https://badgen.net/badge/JIRA/PS-8286/green)](https://jira.percona.com/browse/PS-8286) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8286 Release tasks for PS 8.0.28-20

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1085](https://badgen.net/badge/JIRA/PSMDB-1085/green)](https://jira.percona.com/browse/PSMDB-1085) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1085 update psmdb-4.2 version

percona-backup-mongodb/Dockerfile
[![PBM-857](https://badgen.net/badge/JIRA/PBM-857/green)](https://jira.percona.com/browse/PBM-857) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-857 update pbm version

percona-backup-mongodb/Dockerfile
[![PBM-899](https://badgen.net/badge/JIRA/PBM-899/green)](https://jira.percona.com/browse/PBM-899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-899 update pbm version

postgresql-containers/bin/postgres-ha/sql/pgbouncer/pgbouncer-expose-postgres.sql, postgresql-containers/bin/postgres-ha/sql/pgbouncer/pgbouncer-expose-superusers.sql
[![K8SPG-196](https://badgen.net/badge/JIRA/K8SPG-196/green)](https://jira.percona.com/browse/K8SPG-196) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-196: Add pgbouncer install script to expose superusers

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-3971](https://badgen.net/badge/JIRA/PXC-3971/green)](https://jira.percona.com/browse/PXC-3971) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-3971 Release tasks for PXC 8.0.28-19

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-1062](https://badgen.net/badge/JIRA/K8SPXC-1062/green)](https://jira.percona.com/browse/K8SPXC-1062) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* handle SIGTERM instead of SIGINT
* create 'backup' lib
* add timestamp to the log messages
* add 'set -m' to force xbcloud to its own group (PXC-3986)
=> K8SPXC-1062 change run_backup.sh for PXC 8.0 to handle SIGTERM instead of SIGINT

test/tests/mongo-tls-auth/run.sh, test/tests/mongo-tls-basics/run.sh
[![PSMDB-1099](https://badgen.net/badge/JIRA/PSMDB-1099/green)](https://jira.percona.com/browse/PSMDB-1099) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The fix was taken from upstream docker-library/official-images repo:
https://github.com/docker-library/official-images/pull/12745
=> PSMDB-1099 fix tls tests for mongo 4.4.15

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1099](https://badgen.net/badge/JIRA/PSMDB-1099/green)](https://jira.percona.com/browse/PSMDB-1099) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1099 update psmdb-4.4 version

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1062](https://badgen.net/badge/JIRA/K8SPXC-1062/green)](https://jira.percona.com/browse/K8SPXC-1062) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1062 update dependencies

percona-server-8.0/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile
[![CLOUD-719](https://badgen.net/badge/JIRA/CLOUD-719/green)](https://jira.percona.com/browse/CLOUD-719) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-719 add tar to dep to fix 'kubectl cp' command

postgresql-containers/build/postgres-ha/Dockerfile, postgresql-containers/conf/postgres_common/postgres/postgresql.conf.template, postgresql-containers/conf/postgres_common/postgres/postgresql.conf.template.nopgaudit
[![K8SPG-241](https://badgen.net/badge/JIRA/K8SPG-241/green)](https://jira.percona.com/browse/K8SPG-241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-241 improve pg_stat_monitor configuration

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.debug, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/LICENSE, percona-server-mongodb-6.0/README-build.md, percona-server-mongodb-6.0/README.md, percona-server-mongodb-6.0/ps-entry.sh
[![PSMDB-1107](https://badgen.net/badge/JIRA/PSMDB-1107/green)](https://jira.percona.com/browse/PSMDB-1107) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1107 add psmdb-6.0 docker(initial commit)

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-8324](https://badgen.net/badge/JIRA/PS-8324/green)](https://jira.percona.com/browse/PS-8324) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8324 Release tasks for PS 8.0.29-21

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1114](https://badgen.net/badge/JIRA/PSMDB-1114/green)](https://jira.percona.com/browse/PSMDB-1114) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1114 update psmdb-50 version

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-8346](https://badgen.net/badge/JIRA/PS-8346/green)](https://jira.percona.com/browse/PS-8346) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8346 Release tasks for PS-5.7.39-42

mysql-router/Dockerfile, mysql-router/dockerdir/entrypoint.sh
[![K8SPS-82](https://badgen.net/badge/JIRA/K8SPS-82/green)](https://jira.percona.com/browse/K8SPS-82) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-109: Add Dockerfile for MySQL Router

proxysql/Dockerfile
[![PSQLADM-413](https://badgen.net/badge/JIRA/PSQLADM-413/green)](https://jira.percona.com/browse/PSQLADM-413) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**_perconalab/proxysql2:2.4.2-test_**
=> PSQLADM-413 percona-scheduler-admin fails missing my_print_defaults

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8
[![DISTMONGO-171](https://badgen.net/badge/JIRA/DISTMONGO-171/green)](https://jira.percona.com/browse/DISTMONGO-171) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMONGO-171 restore group for mongodb user

.github/workflows/trivy_by_cron.yml, .github/workflows/trivy_scan.yml
[![ENG-1122](https://badgen.net/badge/JIRA/ENG-1122/green)](https://jira.percona.com/browse/ENG-1122) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
1. Added trivy_scan.yml action for scanning containers on
push/pull_request events.
2. Added trivy_by_cron.yml action for scanning containers
for all products by cron(every night at 01:30).
=> ENG-1122 ADD GHA for container vulnerability scan

mysql-router/dockerdir/entrypoint.sh
[![K8SPS-132](https://badgen.net/badge/JIRA/K8SPS-132/green)](https://jira.percona.com/browse/K8SPS-132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-132: Enable HTTP server for MySQL router

.github/workflows/trivy_scan.yml
[![ENG-1122](https://badgen.net/badge/JIRA/ENG-1122/green)](https://jira.percona.com/browse/ENG-1122) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-1122 improvement: generate scan jobs only for uniq products

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.ubi8
[![PS-8364](https://badgen.net/badge/JIRA/PS-8364/green)](https://jira.percona.com/browse/PS-8364) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8364 Missing data directory for ICU regular expressions

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8
[![DISTMONGO-163](https://badgen.net/badge/JIRA/DISTMONGO-163/green)](https://jira.percona.com/browse/DISTMONGO-163) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMONGO-163 v2 Wrong user permissions in the container

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![DISTMONGO-174](https://badgen.net/badge/JIRA/DISTMONGO-174/green)](https://jira.percona.com/browse/DISTMONGO-174) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMONGO-174 Create and build packages for PDMDB 4.4.16

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-4011](https://badgen.net/badge/JIRA/PXC-4011/green)](https://jira.percona.com/browse/PXC-4011) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4011 Release tasks for PXC 5.7.39

mysql-router/dockerdir/entrypoint.sh
[![K8SPS-132](https://badgen.net/badge/JIRA/K8SPS-132/green)](https://jira.percona.com/browse/K8SPS-132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-132: Disable mysql router http server

percona-server-mongodb-4.4/Dockerfile.k8s
[![DISTMONGO-174](https://badgen.net/badge/JIRA/DISTMONGO-174/green)](https://jira.percona.com/browse/DISTMONGO-174) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Fix-docker-k8s-mdb-4.4.16

proxysql/Dockerfile
[![PSQLADM-7](https://badgen.net/badge/JIRA/PSQLADM-7/green)](https://jira.percona.com/browse/PSQLADM-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSQLADM-7 Update proxysql version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1127](https://badgen.net/badge/JIRA/PSMDB-1127/green)](https://jira.percona.com/browse/PSMDB-1127) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1127 update psmdb-5.0 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![K8SPSMDB-515](https://badgen.net/badge/JIRA/K8SPSMDB-515/green)](https://jira.percona.com/browse/K8SPSMDB-515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-515: Install js-yaml for PSMDB 4.2

percona-distribution-postgresql-11/Dockerfile, percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-14/Dockerfile
[![DISTPG-452](https://badgen.net/badge/JIRA/DISTPG-452/green)](https://jira.percona.com/browse/DISTPG-452) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTPG-452 Update pg dockers

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1132](https://badgen.net/badge/JIRA/PSMDB-1132/green)](https://jira.percona.com/browse/PSMDB-1132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1132 update psmdb-4.2 version

orchestrator/dockerdir/etc/orchestrator/orchestrator.conf.json, percona-toolkit/Dockerfile
[![K8SPS-17](https://badgen.net/badge/JIRA/K8SPS-17/green)](https://jira.percona.com/browse/K8SPS-17) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-17: pt-heartbeat integration

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-4022](https://badgen.net/badge/JIRA/PXC-4022/green)](https://jira.percona.com/browse/PXC-4022) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4022 Release tasks for PXC 8.0.29-21

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-776](https://badgen.net/badge/JIRA/PSMDB-776/green)](https://jira.percona.com/browse/PSMDB-776) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-776 Add percona-server-mongodb-tools to Dockerfile for percona-server-mongodb 4.2/4.4/5.0

percona-backup-mongodb/Dockerfile
[![PBM-953](https://badgen.net/badge/JIRA/PBM-953/green)](https://jira.percona.com/browse/PBM-953) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-953 update pbm version

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-257](https://badgen.net/badge/JIRA/K8SPG-257/green)](https://jira.percona.com/browse/K8SPG-257) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-257 fix stanza

haproxy/Dockerfile, orchestrator/Dockerfile, percona-toolkit/Dockerfile
[![K8SPS-171](https://badgen.net/badge/JIRA/K8SPS-171/green)](https://jira.percona.com/browse/K8SPS-171) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-171 - Update images for PS operator 0.3.0 release

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1145](https://badgen.net/badge/JIRA/PSMDB-1145/green)](https://jira.percona.com/browse/PSMDB-1145) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1145 update psmdb-5.0 version

percona-backup-mongodb/Dockerfile
[![PBM-985](https://badgen.net/badge/JIRA/PBM-985/green)](https://jira.percona.com/browse/PBM-985) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-985. Update pbm version

percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-15/LICENSE, percona-distribution-postgresql-15/README-build.md, percona-distribution-postgresql-15/README.md, percona-distribution-postgresql-15/entrypoint.sh
[![DISTPG-442](https://badgen.net/badge/JIRA/DISTPG-442/green)](https://jira.percona.com/browse/DISTPG-442) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTPG-442 Add pg-15 docker

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/ps-entry.sh
[![PSMDB-1150](https://badgen.net/badge/JIRA/PSMDB-1150/green)](https://jira.percona.com/browse/PSMDB-1150) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
1. Update docker files to use repo ENV variable
2. update ps-entry.sh to use mongosh instead of mongo
=> PSMDB-1150 update psmdb-6.0 docker

percona-server-8.0/Dockerfile
[![RM-1085](https://badgen.net/badge/JIRA/RM-1085/green)](https://jira.percona.com/browse/RM-1085) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1085 PS-8.0.30-22

percona-backup-mongodb/Dockerfile
[![PBM-990](https://badgen.net/badge/JIRA/PBM-990/green)](https://jira.percona.com/browse/PBM-990) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-990. Update pbm version

fluentbit/Dockerfile, fluentbit/dockerdir/entrypoint.sh
[![K8SPXC-982](https://badgen.net/badge/JIRA/K8SPXC-982/green)](https://jira.percona.com/browse/K8SPXC-982) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-982 update fluentbit to 2.0.1

percona-xtrabackup-8.0/Dockerfile
[![PXB-2907](https://badgen.net/badge/JIRA/PXB-2907/green)](https://jira.percona.com/browse/PXB-2907) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2907 Release tasks for PXB-8.0.30-23

percona-xtradb-cluster-5.7-backup/recovery-cloud.sh
[![K8SPXC-1005](https://badgen.net/badge/JIRA/K8SPXC-1005/green)](https://jira.percona.com/browse/K8SPXC-1005) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1005 remove unsupported options from 5.7 recovery-cloud.sh

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-5.0/Dockerfile
[![PSMDB-1093](https://badgen.net/badge/JIRA/PSMDB-1093/green)](https://jira.percona.com/browse/PSMDB-1093) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1093 possibilty to build image for testing/experimental repos

percona-server-5.7/Dockerfile-dockerhub
[![ENG-7](https://badgen.net/badge/JIRA/ENG-7/green)](https://jira.percona.com/browse/ENG-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-7 ps57 docker: change base image centos8->OL8

percona-server-8.0/Dockerfile.ubi8
[![PS-8463](https://badgen.net/badge/JIRA/PS-8463/green)](https://jira.percona.com/browse/PS-8463) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8463 Release tasks for PS 8.0.30-22

percona-toolkit/Dockerfile
[![K8SPXC-1136](https://badgen.net/badge/JIRA/K8SPXC-1136/green)](https://jira.percona.com/browse/K8SPXC-1136) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1136 add tar to percona-toolkit image

proxysql/dockerdir/entrypoint.sh
[![K8SPXC-1097](https://badgen.net/badge/JIRA/K8SPXC-1097/green)](https://jira.percona.com/browse/K8SPXC-1097) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1097: Escape more characters in passwords

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-1005](https://badgen.net/badge/JIRA/K8SPXC-1005/green)](https://jira.percona.com/browse/K8SPXC-1005) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1005
Removed redundant lines and added missing `request_streaming`
=> K8SPXC-1005: fix azure backup for 5.7

percona-distribution-postgresql-11/README.md, percona-distribution-postgresql-12/README.md, percona-distribution-postgresql-13/README.md, percona-distribution-postgresql-14/README.md, percona-distribution-postgresql-15/README.md
[![DISTPG-520](https://badgen.net/badge/JIRA/DISTPG-520/green)](https://jira.percona.com/browse/DISTPG-520) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Added the password variable to How to start a container
modified:   percona-distribution-postgresql-11/README.md
modified:   percona-distribution-postgresql-12/README.md
modified:   percona-distribution-postgresql-13/README.md
modified:   percona-distribution-postgresql-14/README.md
modified:   percona-distribution-postgresql-15/README.md
=> DISTPG-520 Updated the Docker readme

percona-server-5.7/Dockerfile
[![PS-8499](https://badgen.net/badge/JIRA/PS-8499/green)](https://jira.percona.com/browse/PS-8499) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8499 Release tasks for PS 5.7.40-43

mysql-router/Dockerfile
[![DISTMYSQL-209](https://badgen.net/badge/JIRA/DISTMYSQL-209/green)](https://jira.percona.com/browse/DISTMYSQL-209) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMYSQL-209 Update dockerfile for mysql-router image

percona-xtradb-cluster-5.7-backup/recovery-cloud.sh
[![K8SPXC-1005](https://badgen.net/badge/JIRA/K8SPXC-1005/green)](https://jira.percona.com/browse/K8SPXC-1005) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1005 fix encrypted backupt for PXC 5.7

percona-xtrabackup-2.4/Dockerfile
[![PXB-2933](https://badgen.net/badge/JIRA/PXB-2933/green)](https://jira.percona.com/browse/PXB-2933) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2933 Release tasks for PXB-2.4.27

fluentbit/Dockerfile, haproxy/Dockerfile, percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-1158](https://badgen.net/badge/JIRA/K8SPXC-1158/green)](https://jira.percona.com/browse/K8SPXC-1158) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1158 fix CVE-2022-42898 vulnerability

percona-server-mongodb-6.0/Dockerfile.aarch64
[![PSMDB-1019](https://badgen.net/badge/JIRA/PSMDB-1019/green)](https://jira.percona.com/browse/PSMDB-1019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1019 create Dockerfile for psmdb-60 aarch64

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![RM-1087](https://badgen.net/badge/JIRA/RM-1087/green)](https://jira.percona.com/browse/RM-1087) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1087 PXC-8.0.30-22

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64
[![PS-8320](https://badgen.net/badge/JIRA/PS-8320/green)](https://jira.percona.com/browse/PS-8320) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8320 Update ps-build scripts to use new docker

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1190](https://badgen.net/badge/JIRA/PSMDB-1190/green)](https://jira.percona.com/browse/PSMDB-1190) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1190. Update psmdb-4.4 version

haproxy/Dockerfile, percona-toolkit/Dockerfile
[![K8SPS-188](https://badgen.net/badge/JIRA/K8SPS-188/green)](https://jira.percona.com/browse/K8SPS-188) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-188 - Set versions for PS operator 0.4.0 release

percona-backup-mongodb/Dockerfile
[![PBM-1013](https://badgen.net/badge/JIRA/PBM-1013/green)](https://jira.percona.com/browse/PBM-1013) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1013. Update pbm version

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64, percona-server-8.0/Dockerfile.ubi8
[![PS-8576](https://badgen.net/badge/JIRA/PS-8576/green)](https://jira.percona.com/browse/PS-8576) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8576 Home folder /home/mysql does not exist or is not accessible

haproxy/Dockerfile, percona-toolkit/Dockerfile
[![K8SPS-188](https://badgen.net/badge/JIRA/K8SPS-188/green)](https://jira.percona.com/browse/K8SPS-188) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-188 - Update for PS Operator release 0.4.0

percona-xtrabackup-8.0/Dockerfile
[![PXB-2974](https://badgen.net/badge/JIRA/PXB-2974/green)](https://jira.percona.com/browse/PXB-2974) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2974 Release tasks for PXB-8.0.31-24

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8
[![PSMDB-1205](https://badgen.net/badge/JIRA/PSMDB-1205/green)](https://jira.percona.com/browse/PSMDB-1205) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1205. Update psmdb-6.0 version

orchestrator/Dockerfile, proxysql/Dockerfile
[![DISTMYSQL-275](https://badgen.net/badge/JIRA/DISTMYSQL-275/green)](https://jira.percona.com/browse/DISTMYSQL-275) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMYSQL-275 Create and build packages for PDPS-8.0.31-23

percona-xtrabackup-8.0/Dockerfile
[![PXB-2992](https://badgen.net/badge/JIRA/PXB-2992/green)](https://jira.percona.com/browse/PXB-2992) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2992 install lz4 zstd on PXB image

mysql-router/Dockerfile
[![PS-8603](https://badgen.net/badge/JIRA/PS-8603/green)](https://jira.percona.com/browse/PS-8603) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8603 Release tasks for PS 8.0.31-23

percona-server-8.0/Dockerfile
[![PS-8603](https://badgen.net/badge/JIRA/PS-8603/green)](https://jira.percona.com/browse/PS-8603) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://github.com/docker-library/official-images/pull/14053#issuecomment-1424682577
=> PS-8603 request from docker-library

percona-backup-mongodb/Dockerfile
[![PBM-1049](https://badgen.net/badge/JIRA/PBM-1049/green)](https://jira.percona.com/browse/PBM-1049) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1049. Update pbm version

percona-xtrabackup-8.0/Dockerfile
[![PXB-2996](https://badgen.net/badge/JIRA/PXB-2996/green)](https://jira.percona.com/browse/PXB-2996) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-2996 Release PXB 8.0.32-26

percona-server-5.6/README.md, percona-server-5.7/README.md, percona-server-8.0/README.md, percona-server-master-slave/README.md
Hi, I fixed the product logos using the new branding. Cheers.
=> fix product logo to new branding

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1214](https://badgen.net/badge/JIRA/PSMDB-1214/green)](https://jira.percona.com/browse/PSMDB-1214) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1214. Update psmdb-4.2 version

postgresql-containers/bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-gcs.sh, postgresql-containers/bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-s3.sh
[![K8SPG-290](https://badgen.net/badge/JIRA/K8SPG-290/green)](https://jira.percona.com/browse/K8SPG-290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-290 add timeout for 'pgbackrest archive-push' command

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-4159](https://badgen.net/badge/JIRA/PXC-4159/green)](https://jira.percona.com/browse/PXC-4159) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4159 update pxc-80 version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1215](https://badgen.net/badge/JIRA/PSMDB-1215/green)](https://jira.percona.com/browse/PSMDB-1215) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1215. Update psmdb-5.0 version

percona-server-8.0/Dockerfile
[![PS-8657](https://badgen.net/badge/JIRA/PS-8657/green)](https://jira.percona.com/browse/PS-8657) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8657 Release tasks for PS-8.0.32-24

percona-toolkit/Dockerfile
[![ENG-1174](https://badgen.net/badge/JIRA/ENG-1174/green)](https://jira.percona.com/browse/ENG-1174) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-1174 Fix toolkit build on release repos

percona-server-mongodb/Dockerfile, test/detect-images.sh
[![ENG-1174](https://badgen.net/badge/JIRA/ENG-1174/green)](https://jira.percona.com/browse/ENG-1174) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-1174 percona-docker repo issues with repositories

percona-xtrabackup-2.4/Dockerfile
[![PXB-3021](https://badgen.net/badge/JIRA/PXB-3021/green)](https://jira.percona.com/browse/PXB-3021) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-3021 Release tasks for PXB-2.4.28

percona-xtrabackup-8.0/Dockerfile
[![PXB-3020](https://badgen.net/badge/JIRA/PXB-3020/green)](https://jira.percona.com/browse/PXB-3020) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-3020 Release tasks for PXB-8.0.32-26

mysql-router/Dockerfile
[![K8SPS-217](https://badgen.net/badge/JIRA/K8SPS-217/green)](https://jira.percona.com/browse/K8SPS-217) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* router pod can't stop gracefully and kubelet always
triggers forcible shutdown
=> K8SPS-217 router pod can't stop gracefully

haproxy/Dockerfile, mysql-router/Dockerfile, orchestrator/Dockerfile, percona-toolkit/Dockerfile
[![K8SPS-238](https://badgen.net/badge/JIRA/K8SPS-238/green)](https://jira.percona.com/browse/K8SPS-238) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPS-238 - Update docker images for router, orchestrator, toolkit and haproxy

percona-backup-mongodb/Dockerfile.ubi9
[![K8SPSMDB-847](https://badgen.net/badge/JIRA/K8SPSMDB-847/green)](https://jira.percona.com/browse/K8SPSMDB-847) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-847-Migrate-containers-to-UBI9-base-image

percona-server-8.0/Dockerfile
[![PS-8657](https://badgen.net/badge/JIRA/PS-8657/green)](https://jira.percona.com/browse/PS-8657) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8657 apply official images requirements

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1232](https://badgen.net/badge/JIRA/PSMDB-1232/green)](https://jira.percona.com/browse/PSMDB-1232) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1232. Update psmdb-6.0 version

percona-xtradb-cluster-8.0/Dockerfile
[![PXC-4190](https://badgen.net/badge/JIRA/PXC-4190/green)](https://jira.percona.com/browse/PXC-4190) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4190 Release tasks ticket for PXC 8.0.31-23.2

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.debug, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8, percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.debug, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.debug, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.debug, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1242](https://badgen.net/badge/JIRA/PSMDB-1242/green)](https://jira.percona.com/browse/PSMDB-1242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1242 Missing cyrus-sasl-gssapi in PSMDB docker images

percona-xtradb-cluster-5.7-backup/recovery-cloud.sh, percona-xtradb-cluster-8.0-backup/recovery-cloud.sh
[![K8SPXC-1199](https://badgen.net/badge/JIRA/K8SPXC-1199/green)](https://jira.percona.com/browse/K8SPXC-1199) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1199 add possibility of restoring backup without container option

percona-postgis/Dockerfile, percona-postgis/initdb-postgis.sh, percona-postgis/update-postgis.sh
[![DISTPG-494](https://badgen.net/badge/JIRA/DISTPG-494/green)](https://jira.percona.com/browse/DISTPG-494) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Add dockerfile and scripts for postgis docker image

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-282](https://badgen.net/badge/JIRA/K8SPG-282/green)](https://jira.percona.com/browse/K8SPG-282) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-282 use patroni 3.X for PG15

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1083](https://badgen.net/badge/JIRA/PBM-1083/green)](https://jira.percona.com/browse/PBM-1083) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1083. Update pbm version

haproxy/Dockerfile
[![DISTMYSQL-299](https://badgen.net/badge/JIRA/DISTMYSQL-299/green)](https://jira.percona.com/browse/DISTMYSQL-299) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMYSQL-299 Create and build packages for PDPXC 8.0.32-24

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile, postgresql-containers/build/postgres/Dockerfile, postgresql-containers/go.mod
[![K8SPG-338](https://badgen.net/badge/JIRA/K8SPG-338/green)](https://jira.percona.com/browse/K8SPG-338) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-338 update go version to 1.20

mysql-router/Dockerfile, mysql-router/dockerdir/entrypoint.sh
[![PS-8638](https://badgen.net/badge/JIRA/PS-8638/green)](https://jira.percona.com/browse/PS-8638) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8638 Changes for mysqlrouter to work as a part of PS distribution

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-5](https://badgen.net/badge/JIRA/PSMDB-5/green)](https://jira.percona.com/browse/PSMDB-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1251. Update psmdb-5.0 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-4](https://badgen.net/badge/JIRA/PSMDB-4/green)](https://jira.percona.com/browse/PSMDB-4) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1252. Update psmdb-4.4 version

.github/workflows/trivy_scan_pmm.yml
[![ENG-7](https://badgen.net/badge/JIRA/ENG-7/green)](https://jira.percona.com/browse/ENG-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-7 pmm-server docker scan

.github/workflows/trivy_scan_pmm.yml
[![ENG-7](https://badgen.net/badge/JIRA/ENG-7/green)](https://jira.percona.com/browse/ENG-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> ENG-7 update scanning

percona-server-5.7/Dockerfile
[![PS-8765](https://badgen.net/badge/JIRA/PS-8765/green)](https://jira.percona.com/browse/PS-8765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8765-Release tasks for PS 5.7.42-45

percona-xtradb-cluster-8.0-backup/backup.sh
[![K8SPXC-976](https://badgen.net/badge/JIRA/K8SPXC-976/green)](https://jira.percona.com/browse/K8SPXC-976) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* when the script can't connect to the cluster we
can see the error output from DB
=> K8SPXC-976 improve exit code handling

percona-xtrabackup-8.0/Dockerfile
[![PXB-3054](https://badgen.net/badge/JIRA/PXB-3054/green)](https://jira.percona.com/browse/PXB-3054) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-3054 Release tasks for PXB-8.0.33-27

proxysql/Dockerfile
[![RM-1201](https://badgen.net/badge/JIRA/RM-1201/green)](https://jira.percona.com/browse/RM-1201) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1201 ProxySQL 2.5.1

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-6](https://badgen.net/badge/JIRA/PSMDB-6/green)](https://jira.percona.com/browse/PSMDB-6) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1267. Update psmdb-6.0 version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-5](https://badgen.net/badge/JIRA/PSMDB-5/green)](https://jira.percona.com/browse/PSMDB-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1271. Update psmdb-5.0 version

percona-toolkit/Dockerfile
[![PT-3](https://badgen.net/badge/JIRA/PT-3/green)](https://jira.percona.com/browse/PT-3) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PT-3.5.3-1

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-4](https://badgen.net/badge/JIRA/PSMDB-4/green)](https://jira.percona.com/browse/PSMDB-4) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1273. Update psmdb4.4 version

fluentbit/Dockerfile, fluentbit/dockerdir/usr/local/bin/postrotate-mysql.sh
[![K8SPXC-1255](https://badgen.net/badge/JIRA/K8SPXC-1255/green)](https://jira.percona.com/browse/K8SPXC-1255) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* update fluentbit to 2.1.4
=> K8SPXC-1255 flush audit log if plugin is loaded

percona-toolkit/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PXC-4240](https://badgen.net/badge/JIRA/PXC-4240/green)](https://jira.percona.com/browse/PXC-4240) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4240 release tasks ticket for pxc 5.7.42

fluentbit/Dockerfile
[![K8SPXC-1257](https://badgen.net/badge/JIRA/K8SPXC-1257/green)](https://jira.percona.com/browse/K8SPXC-1257) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* update fluentbit to 2.1.5
=> K8SPXC-1257 use el9 for fluentbit images

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1146](https://badgen.net/badge/JIRA/PBM-1146/green)](https://jira.percona.com/browse/PBM-1146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1146. Update pbm version

percona-xtrabackup-8.0/Dockerfile
[![RM-1174](https://badgen.net/badge/JIRA/RM-1174/green)](https://jira.percona.com/browse/RM-1174) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1174 pxb 8.0.33 28

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![RM-1241](https://badgen.net/badge/JIRA/RM-1241/green)](https://jira.percona.com/browse/RM-1241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1241 ProxySQL-2.5.4

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1160](https://badgen.net/badge/JIRA/PBM-1160/green)](https://jira.percona.com/browse/PBM-1160) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1160. Update pbm version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64
[![PSMDB-1304](https://badgen.net/badge/JIRA/PSMDB-1304/green)](https://jira.percona.com/browse/PSMDB-1304) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1304. Install updates to prevent CVE-2023-38408

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1304](https://badgen.net/badge/JIRA/PSMDB-1304/green)](https://jira.percona.com/browse/PSMDB-1304) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1304. Update psmdb6.0 version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1312](https://badgen.net/badge/JIRA/PSMDB-1312/green)](https://jira.percona.com/browse/PSMDB-1312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1312. Update psmdb-5.0 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1300](https://badgen.net/badge/JIRA/PSMDB-1300/green)](https://jira.percona.com/browse/PSMDB-1300) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1300. Update psmdb4.4 version

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-8875](https://badgen.net/badge/JIRA/PS-8875/green)](https://jira.percona.com/browse/PS-8875) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-8875 Release tasks ticket for PS-5.7.43-47

percona-xtrabackup-8.0/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile
[![RM-1175](https://badgen.net/badge/JIRA/RM-1175/green)](https://jira.percona.com/browse/RM-1175) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1175 PXB-8.0.34-29

percona-server-mongodb-5.0/Dockerfile.aarch64
[![PSMDB-1017](https://badgen.net/badge/JIRA/PSMDB-1017/green)](https://jira.percona.com/browse/PSMDB-1017) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1017 Add dockerfile for PSMDB 5.0 arm64

percona-server-mongodb-4.4/Dockerfile.aarch64
[![PSMDB1017-44](https://badgen.net/badge/JIRA/PSMDB1017-44/green)](https://jira.percona.com/browse/PSMDB1017-44) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1017 Add dockerfile for PSMDB 4.4 arm64

percona-xtradb-cluster-5.7/Dockerfile
[![PXC-4295](https://badgen.net/badge/JIRA/PXC-4295/green)](https://jira.percona.com/browse/PXC-4295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4295 Release tasks ticket for PXC 5.7.43

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1328](https://badgen.net/badge/JIRA/PSMDB-1328/green)](https://jira.percona.com/browse/PSMDB-1328) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1328. Update psmdb5.0 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1330](https://badgen.net/badge/JIRA/PSMDB-1330/green)](https://jira.percona.com/browse/PSMDB-1330) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1330. Update psmdb4.4 version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1332](https://badgen.net/badge/JIRA/PSMDB-1332/green)](https://jira.percona.com/browse/PSMDB-1332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1332. Update psmdb6.0 version

percona-backup-mongodb/Dockerfile.aarch64
[![PBM-1138](https://badgen.net/badge/JIRA/PBM-1138/green)](https://jira.percona.com/browse/PBM-1138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1138. PBM ARM, fix kubectl checksum

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1191](https://badgen.net/badge/JIRA/PBM-1191/green)](https://jira.percona.com/browse/PBM-1191) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1191. Update pbm version

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.debug, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9, percona-server-mongodb-7.0/LICENSE, percona-server-mongodb-7.0/README-build.md, percona-server-mongodb-7.0/README.md, percona-server-mongodb-7.0/ps-entry.sh
[![PSMDB-1345](https://badgen.net/badge/JIRA/PSMDB-1345/green)](https://jira.percona.com/browse/PSMDB-1345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1345. Add dockerfile for PSMDB 7.0

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64
[![PSMDB-1355](https://badgen.net/badge/JIRA/PSMDB-1355/green)](https://jira.percona.com/browse/PSMDB-1355) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1355 CVE-2023-3341, CVE-2023-4911 and CVE-2021-40528

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1348](https://badgen.net/badge/JIRA/PSMDB-1348/green)](https://jira.percona.com/browse/PSMDB-1348) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1348. Update psmdb5.0 version

postgresql-containers/build/postgres-ha/Dockerfile, postgresql-containers/build/postgres/Dockerfile
[![K8SPG-443](https://badgen.net/badge/JIRA/K8SPG-443/green)](https://jira.percona.com/browse/K8SPG-443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-443 add other languages support for PG

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1351](https://badgen.net/badge/JIRA/PSMDB-1351/green)](https://jira.percona.com/browse/PSMDB-1351) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1351. Update psmdb6.0 version

percona-xtrabackup-8.1/Dockerfile
[![RM-1176](https://badgen.net/badge/JIRA/RM-1176/green)](https://jira.percona.com/browse/RM-1176) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1176 PXB-8.1

postgresql-containers/build/postgres-ha/Dockerfile
[![K8SPG-434](https://badgen.net/badge/JIRA/K8SPG-434/green)](https://jira.percona.com/browse/K8SPG-434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-434 fix build for postgres-ha image

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, percona-xtradb-cluster-8.0/dockerdir/entrypoint.sh
[![PXC-4319](https://badgen.net/badge/JIRA/PXC-4319/green)](https://jira.percona.com/browse/PXC-4319) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXC-4319 add call home.sh script to pxc server package

haproxy/Dockerfile
[![DISTMYSQL-363](https://badgen.net/badge/JIRA/DISTMYSQL-363/green)](https://jira.percona.com/browse/DISTMYSQL-363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMYSQL-363-Docker-HAproxy-2.8.1-trivy-analyzer-tests-fail

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![PSQLADM-498](https://badgen.net/badge/JIRA/PSQLADM-498/green)](https://jira.percona.com/browse/PSQLADM-498) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSQLADM-498 Wrong versions in Dockerfile

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.debug, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-server-mongodb-5.0/ps-entry.sh
[![PSMDB-1362](https://badgen.net/badge/JIRA/PSMDB-1362/green)](https://jira.percona.com/browse/PSMDB-1362) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1362. Add call home.sh script to PSMDB docker image

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-450](https://badgen.net/badge/JIRA/K8SPG-450/green)](https://jira.percona.com/browse/K8SPG-450) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-450: Disable huge_pages by default

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1371](https://badgen.net/badge/JIRA/PSMDB-1371/green)](https://jira.percona.com/browse/PSMDB-1371) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1371. Update psmdb5.0 version

percona-server-mongodb-3.6/Dockerfile
[![PSMDB-1375](https://badgen.net/badge/JIRA/PSMDB-1375/green)](https://jira.percona.com/browse/PSMDB-1375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1375 percona-docker github action tests failed

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64
[![RM-1284](https://badgen.net/badge/JIRA/RM-1284/green)](https://jira.percona.com/browse/RM-1284) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1284 PS-8.1.0-1

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-5.7-backup/recovery-cloud.sh, percona-xtradb-cluster-5.7-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.0-backup/recovery-cloud.sh, percona-xtradb-cluster-8.0-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-200](https://badgen.net/badge/JIRA/K8SPXC-200/green)](https://jira.percona.com/browse/K8SPXC-200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-200
=> K8SPXC-200: custom options for xtrabackup binaries

percona-xtradb-cluster-5.7-backup/backup.sh, percona-xtradb-cluster-5.7-backup/recovery-cloud.sh, percona-xtradb-cluster-5.7-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.0-backup/recovery-cloud.sh, percona-xtradb-cluster-8.0-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-200](https://badgen.net/badge/JIRA/K8SPXC-200/green)](https://jira.percona.com/browse/K8SPXC-200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-200 custom options should have more priority than default

percona-xtradb-cluster-5.7-backup/backup.sh
[![K8SPXC-200](https://badgen.net/badge/JIRA/K8SPXC-200/green)](https://jira.percona.com/browse/K8SPXC-200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-200 unify backup command for 5.7 and 8.0

orchestrator/Dockerfile, percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64, percona-server-8.0/ps-entry.sh
[![DISTMYSQL-372](https://badgen.net/badge/JIRA/DISTMYSQL-372/green)](https://jira.percona.com/browse/DISTMYSQL-372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> DISTMYSQL-372 Create and build packages for PDPS-8.1.0

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-9004](https://badgen.net/badge/JIRA/PS-9004/green)](https://jira.percona.com/browse/PS-9004) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PS-9004-Release-tasks-for-PS-5.7.44-48

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1205](https://badgen.net/badge/JIRA/PBM-1205/green)](https://jira.percona.com/browse/PBM-1205) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM-1205. PBM-1215. Change default user and add editor for config maintenance

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1377](https://badgen.net/badge/JIRA/PSMDB-1377/green)](https://jira.percona.com/browse/PSMDB-1377) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1377. Update psmdb-7.0 version

percona-toolkit/Dockerfile
[![PT-2103](https://badgen.net/badge/JIRA/PT-2103/green)](https://jira.percona.com/browse/PT-2103) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PT-2103 Official docker image for percona-toolkit

percona-xtrabackup-2.4/Dockerfile
[![PXB-3209](https://badgen.net/badge/JIRA/PXB-3209/green)](https://jira.percona.com/browse/PXB-3209) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PXB-3209 Release tasks for PXB-2.4.29

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1380](https://badgen.net/badge/JIRA/PSMDB-1380/green)](https://jira.percona.com/browse/PSMDB-1380) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PSMDB-1380. Update psmdb6.0 version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1378](https://badgen.net/badge/JIRA/PSMDB-1378/green)](https://jira.percona.com/browse/PSMDB-1378) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1378]: https://perconadev.atlassian.net/browse/PSMDB-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1378. Update psmdb4.4 version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1379](https://badgen.net/badge/JIRA/PSMDB-1379/green)](https://jira.percona.com/browse/PSMDB-1379) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1379]: https://perconadev.atlassian.net/browse/PSMDB-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1379. Update psmdb5.0 version

haproxy/Dockerfile, haproxy/dockerdir/etc/haproxy/haproxy-global.cfg
[![K8SPXC-1335](https://badgen.net/badge/JIRA/K8SPXC-1335/green)](https://jira.percona.com/browse/K8SPXC-1335) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1335]: https://perconadev.atlassian.net/browse/K8SPXC-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1335: Add hard-stop to haproxy global config

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-1263](https://badgen.net/badge/JIRA/K8SPXC-1263/green)](https://jira.percona.com/browse/K8SPXC-1263) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1263]: https://perconadev.atlassian.net/browse/K8SPXC-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1263 fix proxysql image build

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1263](https://badgen.net/badge/JIRA/K8SPXC-1263/green)](https://jira.percona.com/browse/K8SPXC-1263) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1263]: https://perconadev.atlassian.net/browse/K8SPXC-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1263 fix orchestrator pxc5.7 and pxc8.0 images

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-1263](https://badgen.net/badge/JIRA/K8SPXC-1263/green)](https://jira.percona.com/browse/K8SPXC-1263) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1263]: https://perconadev.atlassian.net/browse/K8SPXC-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1263 fix peer-list

percona-xtradb-cluster-8.0/Dockerfile
[![PXC-4357](https://badgen.net/badge/JIRA/PXC-4357/green)](https://jira.percona.com/browse/PXC-4357) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4357]: https://perconadev.atlassian.net/browse/PXC-4357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4357 release tasks ticket for pxc 8.0.35

percona-xtradb-cluster-8.0/Dockerfile
[![PXC-4357](https://badgen.net/badge/JIRA/PXC-4357/green)](https://jira.percona.com/browse/PXC-4357) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This reverts commit 79b986c960932b8e4aad978475a84b26d4cc83c4.
[PXC-4357]: https://perconadev.atlassian.net/browse/PXC-4357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "PXC-4357 release tasks ticket for pxc 8.0.35 (#900)"

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/dockerdir/entrypoint.sh
[![PXC-4357](https://badgen.net/badge/JIRA/PXC-4357/green)](https://jira.percona.com/browse/PXC-4357) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4357]: https://perconadev.atlassian.net/browse/PXC-4357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4357 release tasks ticket for pxc-8.0.35

percona-xtradb-cluster-8.0-backup/run_backup.sh, percona-xtradb-cluster-8.0/Dockerfile
[![K8SPXC-200](https://badgen.net/badge/JIRA/K8SPXC-200/green)](https://jira.percona.com/browse/K8SPXC-200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-200]: https://perconadev.atlassian.net/browse/K8SPXC-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-200 fix run_backup.sh script

percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![K8SPSMDB-1018](https://badgen.net/badge/JIRA/K8SPSMDB-1018/green)](https://jira.percona.com/browse/K8SPSMDB-1018) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPSMDB-1018]: https://perconadev.atlassian.net/browse/K8SPSMDB-1018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1018 fix mongodb builds

haproxy/dockerdir/etc/haproxy/haproxy-global.cfg, haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-1339](https://badgen.net/badge/JIRA/K8SPXC-1339/green)](https://jira.percona.com/browse/K8SPXC-1339) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1339]: https://perconadev.atlassian.net/browse/K8SPXC-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1339: Configure resolvers in Kubernetes

percona-toolkit/Dockerfile
[![PT-2304](https://badgen.net/badge/JIRA/PT-2304/green)](https://jira.percona.com/browse/PT-2304) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PT-2304]: https://perconadev.atlassian.net/browse/PT-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-2304 Missing hostname in PT docker container

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1396](https://badgen.net/badge/JIRA/PSMDB-1396/green)](https://jira.percona.com/browse/PSMDB-1396) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1396]: https://perconadev.atlassian.net/browse/PSMDB-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1396. Update psmdb4.4 version

postgresql-containers/build/postgres-gis/Dockerfile
[![K8SPG-498](https://badgen.net/badge/JIRA/K8SPG-498/green)](https://jira.percona.com/browse/K8SPG-498) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-498]: https://perconadev.atlassian.net/browse/K8SPG-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-498 fix postgres-gis builds

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub
[![PS-9043](https://badgen.net/badge/JIRA/PS-9043/green)](https://jira.percona.com/browse/PS-9043) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PS-9043]: https://perconadev.atlassian.net/browse/PS-9043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-9043 modify telemetry code for official docker images

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1400](https://badgen.net/badge/JIRA/PSMDB-1400/green)](https://jira.percona.com/browse/PSMDB-1400) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1400]: https://perconadev.atlassian.net/browse/PSMDB-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1400 update psmdb-7.0 version

orchestrator/Dockerfile
[![K8SPS-329](https://badgen.net/badge/JIRA/K8SPS-329/green)](https://jira.percona.com/browse/K8SPS-329) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPS-329]: https://perconadev.atlassian.net/browse/K8SPS-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-329 use peer-list from init image

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64, percona-server-8.0/Dockerfile.ubi8
[![PS-9043](https://badgen.net/badge/JIRA/PS-9043/green)](https://jira.percona.com/browse/PS-9043) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PS-9043]: https://perconadev.atlassian.net/browse/PS-9043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-9043 modify telemetry part ps-8.0

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1405](https://badgen.net/badge/JIRA/PSMDB-1405/green)](https://jira.percona.com/browse/PSMDB-1405) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1405]: https://perconadev.atlassian.net/browse/PSMDB-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1405. Update psmdb-5.0 version

fluentbit/dockerdir/usr/local/bin/postrotate-mysql.sh
[![K8SPXC-1350](https://badgen.net/badge/JIRA/K8SPXC-1350/green)](https://jira.percona.com/browse/K8SPXC-1350) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* fix unnesesary TOI DDL operation with flush error logs
during log rotate
[K8SPXC-1350]: https://perconadev.atlassian.net/browse/K8SPXC-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1350 fix unnesesary TOI DDL operation

percona-xtradb-cluster-5.7/dockerdir/etc/mysql/node.cnf, percona-xtradb-cluster-8.0/dockerdir/etc/mysql/node.cnf
[![K8SPXC-1352](https://badgen.net/badge/JIRA/K8SPXC-1352/green)](https://jira.percona.com/browse/K8SPXC-1352) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1352]: https://perconadev.atlassian.net/browse/K8SPXC-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1352: Change default innodb_flush_log_at_trx_commit value

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1407](https://badgen.net/badge/JIRA/PSMDB-1407/green)](https://jira.percona.com/browse/PSMDB-1407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1407]: https://perconadev.atlassian.net/browse/PSMDB-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1407. Update psmdb4.4 version

percona-server-mongodb-4.2/Dockerfile, percona-server-mongodb-4.2/Dockerfile.k8s, percona-server-mongodb-4.2/Dockerfile.ubi8
[![PSMDB-1406](https://badgen.net/badge/JIRA/PSMDB-1406/green)](https://jira.percona.com/browse/PSMDB-1406) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1406]: https://perconadev.atlassian.net/browse/PSMDB-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1406. Update psmdb-4.2 version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1408](https://badgen.net/badge/JIRA/PSMDB-1408/green)](https://jira.percona.com/browse/PSMDB-1408) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1408]: https://perconadev.atlassian.net/browse/PSMDB-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1408. Update psmdb-6.0 version

proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![PSQLADM-508](https://badgen.net/badge/JIRA/PSQLADM-508/green)](https://jira.percona.com/browse/PSQLADM-508) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSQLADM-508]: https://perconadev.atlassian.net/browse/PSQLADM-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PSQLADM-508]: Moved ProxySQL docker image to UBI 9.

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![PXC-4384](https://badgen.net/badge/JIRA/PXC-4384/green)](https://jira.percona.com/browse/PXC-4384) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4384]: https://perconadev.atlassian.net/browse/PXC-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4384 Fetch latest perf package from ALmaLinux repo to fix CVE issues

percona-xtradb-cluster-5.7-backup/Dockerfile
[![K8SPXC-1295](https://badgen.net/badge/JIRA/K8SPXC-1295/green)](https://jira.percona.com/browse/K8SPXC-1295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1295 Add libatomic dependency to xtrabackup Dockerfile

percona-xtradb-cluster-5.7-backup/Dockerfile
[![K8SPXC-1295](https://badgen.net/badge/JIRA/K8SPXC-1295/green)](https://jira.percona.com/browse/K8SPXC-1295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1295 Update Dockerfile to include boost-program-options package

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1241](https://badgen.net/badge/JIRA/PBM-1241/green)](https://jira.percona.com/browse/PBM-1241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1241]: https://perconadev.atlassian.net/browse/PBM-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1241. Update pbm version

fluentbit/Dockerfile, fluentbit/dockerdir/usr/local/bin/postrotate-mysql.sh
[![K8SPXC-1364](https://badgen.net/badge/JIRA/K8SPXC-1364/green)](https://jira.percona.com/browse/K8SPXC-1364) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1364]: https://perconadev.atlassian.net/browse/K8SPXC-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1364 adopt postrotate-mysql.sh for proxy protocol

percona-server-5.7/Dockerfile-pro
[![PKG-14](https://badgen.net/badge/JIRA/PKG-14/green)](https://jira.percona.com/browse/PKG-14) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-14]: https://perconadev.atlassian.net/browse/PKG-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-14 Rework 5.7 tarballs

percona-xtrabackup-8.x/Dockerfile
[![RM-1364](https://badgen.net/badge/JIRA/RM-1364/green)](https://jira.percona.com/browse/RM-1364) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[RM-1364]: https://perconadev.atlassian.net/browse/RM-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RM-1364 PXB-8.3

postgresql-containers/build/postgres-ha/Dockerfile, postgresql-containers/build/postgres/Dockerfile
[![K8SPG-490](https://badgen.net/badge/JIRA/K8SPG-490/green)](https://jira.percona.com/browse/K8SPG-490) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-490]: https://perconadev.atlassian.net/browse/K8SPG-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-490 use the latest patroni for all PG versions

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1267](https://badgen.net/badge/JIRA/PBM-1267/green)](https://jira.percona.com/browse/PBM-1267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1267]: https://perconadev.atlassian.net/browse/PBM-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1267. Update pbm version

percona-server-mongodb-4.4/Dockerfile, percona-server-mongodb-4.4/Dockerfile.aarch64, percona-server-mongodb-4.4/Dockerfile.k8s, percona-server-mongodb-4.4/Dockerfile.ubi8
[![PSMDB-1427](https://badgen.net/badge/JIRA/PSMDB-1427/green)](https://jira.percona.com/browse/PSMDB-1427) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1427]: https://perconadev.atlassian.net/browse/PSMDB-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1427. Update psmdb-4.4 version

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile
[![PXC-4398](https://badgen.net/badge/JIRA/PXC-4398/green)](https://jira.percona.com/browse/PXC-4398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4398]: https://perconadev.atlassian.net/browse/PXC-4398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4398 Release tasks for PXC 8.0.36

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1430](https://badgen.net/badge/JIRA/PSMDB-1430/green)](https://jira.percona.com/browse/PSMDB-1430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1430]: https://perconadev.atlassian.net/browse/PSMDB-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1430. Update psmdb-7.0 version

percona-xtradb-cluster-5.7/Dockerfile-pro
[![PXC-4395](https://badgen.net/badge/JIRA/PXC-4395/green)](https://jira.percona.com/browse/PXC-4395) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4395]: https://perconadev.atlassian.net/browse/PXC-4395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4395 PXC 5.7.44-49 post-EOL 1 refresh Q1 2024

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1428](https://badgen.net/badge/JIRA/PSMDB-1428/green)](https://jira.percona.com/browse/PSMDB-1428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1428]: https://perconadev.atlassian.net/browse/PSMDB-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1428. Update psmdb-5.0 version

proxysql/Dockerfile
[![RM-1376](https://badgen.net/badge/JIRA/RM-1376/green)](https://jira.percona.com/browse/RM-1376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> RM-1376 ProxySQL 2.6.2

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1446](https://badgen.net/badge/JIRA/PSMDB-1446/green)](https://jira.percona.com/browse/PSMDB-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1446]: https://perconadev.atlassian.net/browse/PSMDB-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1446. Update psmdb-7.0 version

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/pgbadger/Dockerfile, postgresql-containers/build/postgres-ha/Dockerfile, postgresql-containers/build/postgres/Dockerfile, postgresql-containers/go.mod
[![K8SPG-561](https://badgen.net/badge/JIRA/K8SPG-561/green)](https://jira.percona.com/browse/K8SPG-561) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-561]: https://perconadev.atlassian.net/browse/K8SPG-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-561 bump go ver to 1.22

percona-distribution-postgresql-11/Dockerfile, percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-15/Dockerfile-ol8, percona-distribution-postgresql-15/Dockerfile-ol9, percona-distribution-postgresql-16/Dockerfile, percona-distribution-postgresql-16/Dockerfile-ol9, percona-distribution-postgresql-16/Dockerfile_back
[![DISTPG-671](https://badgen.net/badge/JIRA/DISTPG-671/green)](https://jira.percona.com/browse/DISTPG-671) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[DISTPG-671]: https://perconadev.atlassian.net/browse/DISTPG-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISTPG-671]: Fixes postgresql container restart issue.

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1462](https://badgen.net/badge/JIRA/PSMDB-1462/green)](https://jira.percona.com/browse/PSMDB-1462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1462]: https://perconadev.atlassian.net/browse/PSMDB-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1462. Remove outdated operator tools

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1468](https://badgen.net/badge/JIRA/PSMDB-1468/green)](https://jira.percona.com/browse/PSMDB-1468) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1468]: https://perconadev.atlassian.net/browse/PSMDB-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1468. Update psmdb-7.0 version

postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-254](https://badgen.net/badge/JIRA/K8SPG-254/green)](https://jira.percona.com/browse/K8SPG-254) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-254]: https://perconadev.atlassian.net/browse/K8SPG-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-254: Add relocate extension script to upgrade image

postgresql-containers/build/pgbackrest-repo/Dockerfile, postgresql-containers/build/pgbackrest/Dockerfile
[![K8SPG-254](https://badgen.net/badge/JIRA/K8SPG-254/green)](https://jira.percona.com/browse/K8SPG-254) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-254]: https://perconadev.atlassian.net/browse/K8SPG-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-254 in PG16.3 percona-pgbackrest rpm creats postgres user

percona-xtrabackup-8.0/Dockerfile
[![PKG-83](https://badgen.net/badge/JIRA/PKG-83/green)](https://jira.percona.com/browse/PKG-83) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-83]: https://perconadev.atlassian.net/browse/PKG-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-83 Create packages for PXB 8.0.35-31

haproxy/Dockerfile
[![K8SPS-301](https://badgen.net/badge/JIRA/K8SPS-301/green)](https://jira.percona.com/browse/K8SPS-301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPS-301]: https://perconadev.atlassian.net/browse/K8SPS-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-301 fix haproxy build

postgresql-containers/build/postgres/Dockerfile, postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-476](https://badgen.net/badge/JIRA/K8SPG-476/green)](https://jira.percona.com/browse/K8SPG-476) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* remove untrusted languages such as plpython
* remove outdated percona-patroni installation
[K8SPG-476]: https://perconadev.atlassian.net/browse/K8SPG-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-476 remove percona-postgresql-plpython rpm

percona-xtrabackup-8.0/Dockerfile
[![PXB-3312](https://badgen.net/badge/JIRA/PXB-3312/green)](https://jira.percona.com/browse/PXB-3312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXB-3312]: https://perconadev.atlassian.net/browse/PXB-3312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXB-3312 perconalab/percona-xtrabackup:8.0.35 contains CVEs

percona-xtradb-cluster-8.0/Dockerfile
[![PXC-4437](https://badgen.net/badge/JIRA/PXC-4437/green)](https://jira.percona.com/browse/PXC-4437) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4437]: https://perconadev.atlassian.net/browse/PXC-4437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4437 xtrabackup binary broken in percona/percona-xtradb-cluster

haproxy/dockerdir/usr/local/bin/check_pxc.sh
[![K8SPXC-1381](https://badgen.net/badge/JIRA/K8SPXC-1381/green)](https://jira.percona.com/browse/K8SPXC-1381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* skip server if wsrep_rejectqueries set to ALL/ALL_KILL
* skip server if wsrep_donorrejectqueries set to ON
[K8SPXC-1381]: https://perconadev.atlassian.net/browse/K8SPXC-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1381 check wsrep_rejectqueries and wsrep_donorrejectqueries var

haproxy/dockerdir/usr/bin/add_pxc_nodes.sh
[![K8SPXC-1330](https://badgen.net/badge/JIRA/K8SPXC-1330/green)](https://jira.percona.com/browse/K8SPXC-1330) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1330]: https://perconadev.atlassian.net/browse/K8SPXC-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1330: Allow configuring HAProxy replicas to be only readers

proxysql/Dockerfile
[![K8SPXC-1337](https://badgen.net/badge/JIRA/K8SPXC-1337/green)](https://jira.percona.com/browse/K8SPXC-1337) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1337 bump go ver for proxysql docker image

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile.k8s, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1337](https://badgen.net/badge/JIRA/K8SPXC-1337/green)](https://jira.percona.com/browse/K8SPXC-1337) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1337]: https://perconadev.atlassian.net/browse/K8SPXC-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1337 bump go ver for pxc5.7 and pxc8.0

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1337](https://badgen.net/badge/JIRA/K8SPXC-1337/green)](https://jira.percona.com/browse/K8SPXC-1337) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1337]: https://perconadev.atlassian.net/browse/K8SPXC-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1337 fix pxc8.0 build

percona-distribution-postgresql-17/Dockerfile, percona-distribution-postgresql-17/Dockerfile-ol9, percona-distribution-postgresql-17/Dockerfile.aarch64, percona-distribution-postgresql-17/Dockerfile_back, percona-distribution-postgresql-17/LICENSE, percona-distribution-postgresql-17/README-build.md, percona-distribution-postgresql-17/README.md, percona-distribution-postgresql-17/entrypoint.sh
[![PG-803](https://badgen.net/badge/JIRA/PG-803/green)](https://jira.percona.com/browse/PG-803) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PG-803]: https://perconadev.atlassian.net/browse/PG-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PG-803]: Adds changes to build PG 17 docker image.

percona-server-8.0/Dockerfile, percona-server-8.0/ps-entry.sh, percona-server-8.0/telemetry-agent-supervisor.sh
[![PKG-32](https://badgen.net/badge/JIRA/PKG-32/green)](https://jira.percona.com/browse/PKG-32) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-32]: https://perconadev.atlassian.net/browse/PKG-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-32 Create PS Docker images with Telemetry Ph1

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/ps-entry.sh, percona-server-mongodb-7.0/telemetry-agent-supervisor.sh
[![PKG-71](https://badgen.net/badge/JIRA/PKG-71/green)](https://jira.percona.com/browse/PKG-71) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-71]: https://perconadev.atlassian.net/browse/PKG-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-71 Docker images for PSMDB with telemetry

percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.debug, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi8, percona-server-mongodb-8.0/Dockerfile.ubi9, percona-server-mongodb-8.0/LICENSE, percona-server-mongodb-8.0/README-build.md, percona-server-mongodb-8.0/README.md, percona-server-mongodb-8.0/ps-entry.sh
[![PSMDB-1481](https://badgen.net/badge/JIRA/PSMDB-1481/green)](https://jira.percona.com/browse/PSMDB-1481) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1481]: https://perconadev.atlassian.net/browse/PSMDB-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1481. Add Dockerfile for PSMDB 8.0

percona-pgbouncer/Dockerfile, percona-pgbouncer/entrypoint.sh
[![PKG-134](https://badgen.net/badge/JIRA/PKG-134/green)](https://jira.percona.com/browse/PKG-134) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-134]: https://perconadev.atlassian.net/browse/PKG-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PKG-134]: Builds Percona pgbouncer docker image.

percona-pgbackrest/Dockerfile
[![PKG-135](https://badgen.net/badge/JIRA/PKG-135/green)](https://jira.percona.com/browse/PKG-135) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-135]: https://perconadev.atlassian.net/browse/PKG-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PKG-135]: Builds Percona pgbackrest docker image.

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64
[![PS-9284](https://badgen.net/badge/JIRA/PS-9284/green)](https://jira.percona.com/browse/PS-9284) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PS-9284]: https://perconadev.atlassian.net/browse/PS-9284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-9284 Release tasks ticket for PS-8.0.37

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1486](https://badgen.net/badge/JIRA/PSMDB-1486/green)](https://jira.percona.com/browse/PSMDB-1486) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1486]: https://perconadev.atlassian.net/browse/PSMDB-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1486. Update psmdb-7.0 version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1485](https://badgen.net/badge/JIRA/PSMDB-1485/green)](https://jira.percona.com/browse/PSMDB-1485) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1485]: https://perconadev.atlassian.net/browse/PSMDB-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1485. Update psmdb-6.0 version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/ps-entry.sh, percona-server-mongodb-6.0/telemetry-agent-supervisor.sh
[![PSMDB-60](https://badgen.net/badge/JIRA/PSMDB-60/green)](https://jira.percona.com/browse/PSMDB-60) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-60]: https://perconadev.atlassian.net/browse/PSMDB-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update PSMDB-60 Dockerfile with telemetry phase-1 changes

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/ps-entry.sh, percona-server-mongodb-5.0/telemetry-agent-supervisor.sh
[![PSMDB-50](https://badgen.net/badge/JIRA/PSMDB-50/green)](https://jira.percona.com/browse/PSMDB-50) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Update PSMDB-50 Dockerfile with telemetry phase-1 changes

fluentbit/Dockerfile, haproxy/Dockerfile
[![K8SPXC-1363](https://badgen.net/badge/JIRA/K8SPXC-1363/green)](https://jira.percona.com/browse/K8SPXC-1363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1363]: https://perconadev.atlassian.net/browse/K8SPXC-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1363 Update versions and Fluent Bit  in Dockerfiles

percona-xtrabackup-8.x/Dockerfile
[![RM-1365](https://badgen.net/badge/JIRA/RM-1365/green)](https://jira.percona.com/browse/RM-1365) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[RM-1365]: https://perconadev.atlassian.net/browse/RM-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RM-1365 PXB-8.4

orchestrator/Dockerfile
[![DISTMYSQL-439](https://badgen.net/badge/JIRA/DISTMYSQL-439/green)](https://jira.percona.com/browse/DISTMYSQL-439) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[DISTMYSQL-439]: https://perconadev.atlassian.net/browse/DISTMYSQL-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DISTMYSQL-439 Create new orxchestrator 3.2.6-14 packages

percona-backup-mongodb/Dockerfile.aarch64
[![CVE-2024](https://badgen.net/badge/JIRA/CVE-2024/green)](https://jira.percona.com/browse/CVE-2024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PBM. Update kubectl to avoid CVE-2024-24790, fix checksum

percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile.aarch64, percona-xtradb-cluster-8.0/Dockerfile
[![PKG-165](https://badgen.net/badge/JIRA/PKG-165/green)](https://jira.percona.com/browse/PKG-165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-165]: https://perconadev.atlassian.net/browse/PKG-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-165 CVEs in xtradb-cluster, haproxy and proxysql images

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1368](https://badgen.net/badge/JIRA/PBM-1368/green)](https://jira.percona.com/browse/PBM-1368) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1368]: https://perconadev.atlassian.net/browse/PBM-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1368. Update pbm version

percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-12/Dockerfile.aarch64, percona-distribution-postgresql-12/entrypoint.sh, percona-distribution-postgresql-12/telemetry-agent-supervisor.sh, percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-13/Dockerfile.aarch64, percona-distribution-postgresql-13/entrypoint.sh, percona-distribution-postgresql-13/telemetry-agent-supervisor.sh, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-14/Dockerfile.aarch64, percona-distribution-postgresql-14/entrypoint.sh, percona-distribution-postgresql-14/telemetry-agent-supervisor.sh, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-15/Dockerfile.aarch64, percona-distribution-postgresql-15/entrypoint.sh, percona-distribution-postgresql-15/telemetry-agent-supervisor.sh, percona-distribution-postgresql-16/Dockerfile, percona-distribution-postgresql-16/Dockerfile.aarch64, percona-distribution-postgresql-16/entrypoint.sh, percona-distribution-postgresql-16/telemetry-agent-supervisor.sh, percona-distribution-postgresql-17/Dockerfile, percona-distribution-postgresql-17/Dockerfile.aarch64, percona-distribution-postgresql-17/entrypoint.sh, percona-distribution-postgresql-17/telemetry-agent-supervisor.sh
[![PKG-72](https://badgen.net/badge/JIRA/PKG-72/green)](https://jira.percona.com/browse/PKG-72) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-72]: https://perconadev.atlassian.net/browse/PKG-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-72 Create PG Docker images with Telemetry Ph1

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1524](https://badgen.net/badge/JIRA/PSMDB-1524/green)](https://jira.percona.com/browse/PSMDB-1524) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1524]: https://perconadev.atlassian.net/browse/PSMDB-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1524. Update psmdb-6.0 version

fluentbit/Dockerfile, haproxy/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, proxysql/Dockerfile
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1446]: https://perconadev.atlassian.net/browse/K8SPXC-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bump distribution version to 8.0.37

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1525](https://badgen.net/badge/JIRA/PSMDB-1525/green)](https://jira.percona.com/browse/PSMDB-1525) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1525]: https://perconadev.atlassian.net/browse/PSMDB-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1525. Update psmdb-7.0 version

percona-server-mongodb-5.0/Dockerfile, percona-server-mongodb-5.0/Dockerfile.aarch64, percona-server-mongodb-5.0/Dockerfile.k8s, percona-server-mongodb-5.0/Dockerfile.ubi8
[![PSMDB-1526](https://badgen.net/badge/JIRA/PSMDB-1526/green)](https://jira.percona.com/browse/PSMDB-1526) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1526]: https://perconadev.atlassian.net/browse/PSMDB-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1526. Update psmdb-5.0 version

percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/post_backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh
[![K8SPXC-1398](https://badgen.net/badge/JIRA/K8SPXC-1398/green)](https://jira.percona.com/browse/K8SPXC-1398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1398]: https://perconadev.atlassian.net/browse/K8SPXC-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1398: Add post-recv script

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-648](https://badgen.net/badge/JIRA/K8SPG-648/green)](https://jira.percona.com/browse/K8SPG-648) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-648]: https://perconadev.atlassian.net/browse/K8SPG-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-648 fix build

postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-648](https://badgen.net/badge/JIRA/K8SPG-648/green)](https://jira.percona.com/browse/K8SPG-648) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-648]: https://perconadev.atlassian.net/browse/K8SPG-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-648 add PG17 to upgrade image

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1403](https://badgen.net/badge/JIRA/PBM-1403/green)](https://jira.percona.com/browse/PBM-1403) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1403]: https://perconadev.atlassian.net/browse/PBM-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1403. Update pbm version

percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/ps-entry.sh, percona-server-mongodb-8.0/telemetry-agent-supervisor.sh
[![PSMDB-80](https://badgen.net/badge/JIRA/PSMDB-80/green)](https://jira.percona.com/browse/PSMDB-80) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-80]: https://perconadev.atlassian.net/browse/PSMDB-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB. Update PSMDB-80 Dockerfile with telemetry phase-1 changes

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1543](https://badgen.net/badge/JIRA/PSMDB-1543/green)](https://jira.percona.com/browse/PSMDB-1543) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1543]: https://perconadev.atlassian.net/browse/PSMDB-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1543. Update psmdb-6.0 version

haproxy/Dockerfile
[![DISTMYSQL-475](https://badgen.net/badge/JIRA/DISTMYSQL-475/green)](https://jira.percona.com/browse/DISTMYSQL-475) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[DISTMYSQL-475]: https://perconadev.atlassian.net/browse/DISTMYSQL-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DISTMYSQL-475 Create and build packages for PDPXC 8.4.0

orchestrator/Dockerfile, proxysql/Dockerfile
[![PSQLADM-542](https://badgen.net/badge/JIRA/PSQLADM-542/green)](https://jira.percona.com/browse/PSQLADM-542) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSQLADM-542]: https://perconadev.atlassian.net/browse/PSQLADM-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSQLADM-542-Packaging-tasks-for-ProxySQL-2.7.1-1.2

percona-server-5.7/Dockerfile-pro
[![PKG-242](https://badgen.net/badge/JIRA/PKG-242/green)](https://jira.percona.com/browse/PKG-242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-242]: https://perconadev.atlassian.net/browse/PKG-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-242 Create packages for PS 5.7 EOL

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1554](https://badgen.net/badge/JIRA/PSMDB-1554/green)](https://jira.percona.com/browse/PSMDB-1554) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1554]: https://perconadev.atlassian.net/browse/PSMDB-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1554. Update psmdb-7.0 version

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1555](https://badgen.net/badge/JIRA/PSMDB-1555/green)](https://jira.percona.com/browse/PSMDB-1555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1555]: https://perconadev.atlassian.net/browse/PSMDB-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1555. Update psmdb-6.0 version

percona-xtradb-cluster-8.4-backup/Dockerfile, percona-xtradb-cluster-8.4-backup/LICENSE, percona-xtradb-cluster-8.4-backup/backup.sh, percona-xtradb-cluster-8.4-backup/get-pxc-state, percona-xtradb-cluster-8.4-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.4-backup/lib/pxc/check-version.sh, percona-xtradb-cluster-8.4-backup/lib/pxc/vault.sh, percona-xtradb-cluster-8.4-backup/post_backup.sh, percona-xtradb-cluster-8.4-backup/recovery-cloud.sh, percona-xtradb-cluster-8.4-backup/recovery-pvc-donor.sh, percona-xtradb-cluster-8.4-backup/recovery-pvc-joiner.sh, percona-xtradb-cluster-8.4-backup/run_backup.sh
[![K8SPXC-1410](https://badgen.net/badge/JIRA/K8SPXC-1410/green)](https://jira.percona.com/browse/K8SPXC-1410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1410]: https://perconadev.atlassian.net/browse/K8SPXC-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1410 add PXC 8.4 backup image

haproxy/Dockerfile, percona-server-5.7/Dockerfile-pro, percona-server-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile
[![PKG-242](https://badgen.net/badge/JIRA/PKG-242/green)](https://jira.percona.com/browse/PKG-242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-242]: https://perconadev.atlassian.net/browse/PKG-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4569 Release task ticket for PXC 8.0.39

postgresql-containers/build/postgres/Dockerfile, postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-652](https://badgen.net/badge/JIRA/K8SPG-652/green)](https://jira.percona.com/browse/K8SPG-652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-652]: https://perconadev.atlassian.net/browse/K8SPG-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-652 fix build for PG17

percona-server-8.0/Dockerfile-dockerhub, percona-server-mongodb-5.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-7.0/Dockerfile-dockerhub, percona-server-mongodb-8.0/Dockerfile-dockerhub
[![PKG-319](https://badgen.net/badge/JIRA/PKG-319/green)](https://jira.percona.com/browse/PKG-319) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-319]: https://perconadev.atlassian.net/browse/PKG-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-319 Add separate dockerfiles for docker official repo images

postgresql-containers/build/postgres-gis/Dockerfile
[![K8SPG-652](https://badgen.net/badge/JIRA/K8SPG-652/green)](https://jira.percona.com/browse/K8SPG-652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-652]: https://perconadev.atlassian.net/browse/K8SPG-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-652 fix misprint for postgres-gis

percona-xtradb-cluster-8.0/Dockerfile.aarch64
[![PKG-319](https://badgen.net/badge/JIRA/PKG-319/green)](https://jira.percona.com/browse/PKG-319) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-319]: https://perconadev.atlassian.net/browse/PKG-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-266 Build PXC arm docker images

percona-xtradb-cluster-8.0-backup/run_backup.sh, percona-xtradb-cluster-8.4-backup/run_backup.sh
[![K8SPXC-1398](https://badgen.net/badge/JIRA/K8SPXC-1398/green)](https://jira.percona.com/browse/K8SPXC-1398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1398]: https://perconadev.atlassian.net/browse/K8SPXC-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1398: Fix checking empty backups

postgresql-containers/build/pgbackrest/Dockerfile, postgresql-containers/build/postgres/Dockerfile
[![K8SPG-652](https://badgen.net/badge/JIRA/K8SPG-652/green)](https://jira.percona.com/browse/K8SPG-652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-652]: https://perconadev.atlassian.net/browse/K8SPG-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-652 fix PG17 build

fluentbit/Dockerfile, haproxy/Dockerfile, proxysql/Dockerfile, proxysql/Dockerfile.k8s
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1446]: https://perconadev.atlassian.net/browse/K8SPXC-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1446 docker images

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.aarch64, percona-xtradb-cluster-8.0/Dockerfile.k8s
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1446]: https://perconadev.atlassian.net/browse/K8SPXC-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1446: remove peer-list from pxc Dockerfiles

percona-server-8.0/Dockerfile-dockerhub, percona-server-8.0/ps-entry-dockerhub.sh, percona-server-mongodb-5.0/Dockerfile-dockerhub, percona-server-mongodb-5.0/ps-entry-dockerhub.sh, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/ps-entry-dockerhub.sh, percona-server-mongodb-7.0/Dockerfile-dockerhub, percona-server-mongodb-7.0/ps-entry-dockerhub.sh, percona-server-mongodb-8.0/Dockerfile-dockerhub, percona-server-mongodb-8.0/ps-entry-dockerhub.sh
[![PKG-319](https://badgen.net/badge/JIRA/PKG-319/green)](https://jira.percona.com/browse/PKG-319) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Adding a separate entrypoint script for docker official-images repo, due to https://github.com/docker-library/official-images/pull/18023#issuecomment-2542598816
[PKG-319]: https://perconadev.atlassian.net/browse/PKG-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-319 Add separate entrypoint scripts for docker official-repo images

percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi8, percona-server-mongodb-8.0/Dockerfile.ubi9
[![PSMDB-1540](https://badgen.net/badge/JIRA/PSMDB-1540/green)](https://jira.percona.com/browse/PSMDB-1540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1540]: https://perconadev.atlassian.net/browse/PSMDB-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1540. Update psmdb-8.0 version

percona-server-8.0/Dockerfile.aarch64
[![DISTMYSQL-494](https://badgen.net/badge/JIRA/DISTMYSQL-494/green)](https://jira.percona.com/browse/DISTMYSQL-494) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[DISTMYSQL-494]: https://perconadev.atlassian.net/browse/DISTMYSQL-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DISTMYSQL-494 Issues with PDPS 8.4.3

percona-server-5.7/Dockerfile, percona-server-5.7/Dockerfile-dockerhub, percona-server-5.7/Dockerfile-pro, percona-server-8.0/Dockerfile, percona-server-8.0/Dockerfile-dockerhub, percona-server-8.0/Dockerfile.aarch64
[![PKG-291](https://badgen.net/badge/JIRA/PKG-291/green)](https://jira.percona.com/browse/PKG-291) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-291]: https://perconadev.atlassian.net/browse/PKG-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PKG-291]: Using UBI 9 base images for PS 5.7 and 8.0.

percona-xtrabackup-8.0/Dockerfile
[![RM-1471](https://badgen.net/badge/JIRA/RM-1471/green)](https://jira.percona.com/browse/RM-1471) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[RM-1471]: https://perconadev.atlassian.net/browse/RM-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RM-1471 PXB 8.0.35-32

postgresql-containers/build/postgres/Dockerfile, postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-699](https://badgen.net/badge/JIRA/K8SPG-699/green)](https://jira.percona.com/browse/K8SPG-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-699]: https://perconadev.atlassian.net/browse/K8SPG-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-699 add percona-pgvector rpms

postgresql-containers/build/postgres/Dockerfile, postgresql-containers/build/upgrade/Dockerfile
[![K8SPG-699](https://badgen.net/badge/JIRA/K8SPG-699/green)](https://jira.percona.com/browse/K8SPG-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-699]: https://perconadev.atlassian.net/browse/K8SPG-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-699 install pgvector for PG17

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-648](https://badgen.net/badge/JIRA/K8SPG-648/green)](https://jira.percona.com/browse/K8SPG-648) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-648]: https://perconadev.atlassian.net/browse/K8SPG-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-648 use the latest patroni ver for all PG versions

percona-distribution-postgresql-12/Dockerfile, percona-distribution-postgresql-12/Dockerfile.aarch64, percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-13/Dockerfile.aarch64, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-14/Dockerfile.aarch64, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-15/Dockerfile.aarch64, percona-distribution-postgresql-16/Dockerfile, percona-distribution-postgresql-16/Dockerfile.aarch64, percona-distribution-postgresql-17/Dockerfile, percona-distribution-postgresql-17/Dockerfile.aarch64
[![PG-1301](https://badgen.net/badge/JIRA/PG-1301/green)](https://jira.percona.com/browse/PG-1301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PG-1301]: https://perconadev.atlassian.net/browse/PG-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PG-1301]: Reinstalls tzdata package.

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-699](https://badgen.net/badge/JIRA/K8SPG-699/green)](https://jira.percona.com/browse/K8SPG-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-699]: https://perconadev.atlassian.net/browse/K8SPG-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-699 fix build

postgresql-containers/build/postgres/Dockerfile
[![K8SPG-699](https://badgen.net/badge/JIRA/K8SPG-699/green)](https://jira.percona.com/browse/K8SPG-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPG-699 add syntax directive

percona-xtradb-cluster-5.7/Dockerfile, percona-xtradb-cluster-5.7/Dockerfile-pro, percona-xtradb-cluster-5.7/Dockerfile.k8s
[![PKG-443](https://badgen.net/badge/JIRA/PKG-443/green)](https://jira.percona.com/browse/PKG-443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-443]: https://perconadev.atlassian.net/browse/PKG-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PKG-443]: Adjusted download path of telnet rpm package.

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9, percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9, percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile-dockerhub, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9, percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi8, percona-server-mongodb-8.0/Dockerfile.ubi9
[![PBM-1471](https://badgen.net/badge/JIRA/PBM-1471/green)](https://jira.percona.com/browse/PBM-1471) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1471]: https://perconadev.atlassian.net/browse/PBM-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1471. PSMDB-1585. PSMDB-1584. PSMDB-1583. Update PSMDB/PBM version

percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.x/Dockerfile
[![PKG-508](https://badgen.net/badge/JIRA/PKG-508/green)](https://jira.percona.com/browse/PKG-508) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-508]: https://perconadev.atlassian.net/browse/PKG-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-508 Add aws cli to PXB images

percona-xtrabackup-8.x/Dockerfile
[![PKG-527](https://badgen.net/badge/JIRA/PKG-527/green)](https://jira.percona.com/browse/PKG-527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-527]: https://perconadev.atlassian.net/browse/PKG-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-527 Wrong PXB version in 8.4.0-2 docker image

percona-xtradb-cluster-5.7-backup/Dockerfile, percona-xtradb-cluster-8.0-backup/Dockerfile, percona-xtradb-cluster-8.4-backup/Dockerfile
[![K8SPXC-1585](https://badgen.net/badge/JIRA/K8SPXC-1585/green)](https://jira.percona.com/browse/K8SPXC-1585) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1585]: https://perconadev.atlassian.net/browse/K8SPXC-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1585 remove kubectl from backup

percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.x/Dockerfile
[![PKG-524](https://badgen.net/badge/JIRA/PKG-524/green)](https://jira.percona.com/browse/PKG-524) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-524]: https://perconadev.atlassian.net/browse/PKG-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-524 Add additional tools for PXB images

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1526](https://badgen.net/badge/JIRA/PBM-1526/green)](https://jira.percona.com/browse/PBM-1526) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1526]: https://perconadev.atlassian.net/browse/PBM-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1526. Update pbm version

percona-pgbackrest/Dockerfile, percona-pgbackrest/pgbackrest.conf, postgresql-containers/build/postgres/Dockerfile
[![K8SPG-613](https://badgen.net/badge/JIRA/K8SPG-613/green)](https://jira.percona.com/browse/K8SPG-613) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-613
[K8SPG-613]: https://perconadev.atlassian.net/browse/K8SPG-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-613: use percona-pgbackrest in the operator

percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.x/Dockerfile
[![PKG-571](https://badgen.net/badge/JIRA/PKG-571/green)](https://jira.percona.com/browse/PKG-571) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-571]: https://perconadev.atlassian.net/browse/PKG-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-571 Add Azure CLI to PXB images

percona-pgbackrest/Dockerfile, percona-pgbouncer/Dockerfile
[![PKG-561](https://badgen.net/badge/JIRA/PKG-561/green)](https://jira.percona.com/browse/PKG-561) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-561]: https://perconadev.atlassian.net/browse/PKG-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PKG-561]: Set release as default repo.

percona-xtradb-cluster-8.4-backup/Dockerfile
[![K8SPXC-1535](https://badgen.net/badge/JIRA/K8SPXC-1535/green)](https://jira.percona.com/browse/K8SPXC-1535) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1535]: https://perconadev.atlassian.net/browse/K8SPXC-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1535: use 8.4.0-1 PXB for PXCO 1.17.0

percona-xtradb-cluster-8.0-backup/backup.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/aws.sh, percona-xtradb-cluster-8.0-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.0-backup/run_backup.sh, percona-xtradb-cluster-8.4-backup/Dockerfile, percona-xtradb-cluster-8.4-backup/backup.sh, percona-xtradb-cluster-8.4-backup/lib/pxc/aws.sh, percona-xtradb-cluster-8.4-backup/lib/pxc/backup.sh, percona-xtradb-cluster-8.4-backup/run_backup.sh
[![K8SPXC-1620](https://badgen.net/badge/JIRA/K8SPXC-1620/green)](https://jira.percona.com/browse/K8SPXC-1620) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1620]: https://perconadev.atlassian.net/browse/K8SPXC-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1620 add retry for cloud storage cleanup

haproxy/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.aarch64, percona-xtradb-cluster-8.4-backup/Dockerfile, percona-xtradb-cluster-8.4/Dockerfile, percona-xtradb-cluster-8.4/Dockerfile.aarch64, percona-xtradb-cluster-8.4/dockerdir/entrypoint.sh, percona-xtradb-cluster-8.4/dockerdir/etc/mysql/node.cnf, proxysql/Dockerfile
[![PKG-394](https://badgen.net/badge/JIRA/PKG-394/green)](https://jira.percona.com/browse/PKG-394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-394]: https://perconadev.atlassian.net/browse/PKG-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-394 Packaging tasks for release - PXC 8.4.4

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile.aarch64
[![PSMDB-1676](https://badgen.net/badge/JIRA/PSMDB-1676/green)](https://jira.percona.com/browse/PSMDB-1676) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1676]: https://perconadev.atlassian.net/browse/PSMDB-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1676. Add labels for RedHat certification

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1664](https://badgen.net/badge/JIRA/PSMDB-1664/green)](https://jira.percona.com/browse/PSMDB-1664) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1664]: https://perconadev.atlassian.net/browse/PSMDB-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1664. Update psmdb-6.0 version

percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile-dockerhub, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi8, percona-server-mongodb-7.0/Dockerfile.ubi9
[![PSMDB-1665](https://badgen.net/badge/JIRA/PSMDB-1665/green)](https://jira.percona.com/browse/PSMDB-1665) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1665]: https://perconadev.atlassian.net/browse/PSMDB-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1665. Update psmdb-7.0 version

percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile-dockerhub, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi8, percona-server-mongodb-8.0/Dockerfile.ubi9
[![PSMDB-1666](https://badgen.net/badge/JIRA/PSMDB-1666/green)](https://jira.percona.com/browse/PSMDB-1666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1666]: https://perconadev.atlassian.net/browse/PSMDB-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1666. Update psmdb-8.0 version

percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.0/pxb-entry.sh, percona-xtrabackup-8.x/Dockerfile, percona-xtrabackup-8.x/pxb-entry.sh
[![PKG-667](https://badgen.net/badge/JIRA/PKG-667/green)](https://jira.percona.com/browse/PKG-667) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-667]: https://perconadev.atlassian.net/browse/PKG-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-667 Enable Phase-0 telemetry for PXB docker images

orchestrator/Dockerfile
[![PKG-666](https://badgen.net/badge/JIRA/PKG-666/green)](https://jira.percona.com/browse/PKG-666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-666]: https://perconadev.atlassian.net/browse/PKG-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DISTMYSQL-520 Create new Orchestrator 3.2.6-17 packages

percona-server-mongodb-6.0/ps-entry-dockerhub.sh, percona-server-mongodb-6.0/ps-entry.sh, percona-server-mongodb-7.0/ps-entry-dockerhub.sh, percona-server-mongodb-7.0/ps-entry.sh, percona-server-mongodb-8.0/ps-entry-dockerhub.sh, percona-server-mongodb-8.0/ps-entry.sh
[![PSMDB-1679](https://badgen.net/badge/JIRA/PSMDB-1679/green)](https://jira.percona.com/browse/PSMDB-1679) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1679]: https://perconadev.atlassian.net/browse/PSMDB-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1679 Fix ReferenceError related to cat with mongosh

percona-xtrabackup-2.4/Dockerfile, percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.x/Dockerfile
[![PKG-565](https://badgen.net/badge/JIRA/PKG-565/green)](https://jira.percona.com/browse/PKG-565) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-565]: https://perconadev.atlassian.net/browse/PKG-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-565 Packaging tasks for release - PXB 8.4.0-3

fluentbit/Dockerfile
[![K8SPSMDB-297](https://badgen.net/badge/JIRA/K8SPSMDB-297/green)](https://jira.percona.com/browse/K8SPSMDB-297) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Connected to: https://github.com/percona/percona-server-mongodb-operator/pull/1936
[K8SPSMDB-297]: https://perconadev.atlassian.net/browse/K8SPSMDB-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-297 install mongosh to fluentbit base image

percona-xtradb-cluster-8.0/Dockerfile.aarch64
[![PKG-673](https://badgen.net/badge/JIRA/PKG-673/green)](https://jira.percona.com/browse/PKG-673) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-673]: https://perconadev.atlassian.net/browse/PKG-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-673 packaging tasks for release pxc-8.0.42

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi8, percona-server-mongodb-6.0/Dockerfile.ubi9
[![PSMDB-1682](https://badgen.net/badge/JIRA/PSMDB-1682/green)](https://jira.percona.com/browse/PSMDB-1682) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PSMDB-1682]: https://perconadev.atlassian.net/browse/PSMDB-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1682. Update psmdb-6.0 version

percona-pgbackrest/Dockerfile, percona-pgbackrest/LICENSE, percona-pgbouncer/Dockerfile, percona-pgbouncer/LICENSE
[![PKG-835](https://badgen.net/badge/JIRA/PKG-835/green)](https://jira.percona.com/browse/PKG-835) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PKG-835 Invalid RedHats labels in Images - PgBouncer and PgBackrest

percona-server-mongodb-6.0/Dockerfile, percona-server-mongodb-6.0/Dockerfile-dockerhub, percona-server-mongodb-6.0/Dockerfile.aarch64, percona-server-mongodb-6.0/Dockerfile.k8s, percona-server-mongodb-6.0/Dockerfile.ubi9, percona-server-mongodb-7.0/Dockerfile, percona-server-mongodb-7.0/Dockerfile-dockerhub, percona-server-mongodb-7.0/Dockerfile.aarch64, percona-server-mongodb-7.0/Dockerfile.k8s, percona-server-mongodb-7.0/Dockerfile.ubi9, percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile-dockerhub, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi9
[![PKG-830](https://badgen.net/badge/JIRA/PKG-830/green)](https://jira.percona.com/browse/PKG-830) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PKG-830 PSMDB images is broken due to an outdated version of numactl

percona-xtradb-cluster-8.4/Dockerfile.aarch64
[![PKG-675](https://badgen.net/badge/JIRA/PKG-675/green)](https://jira.percona.com/browse/PKG-675) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-675]: https://perconadev.atlassian.net/browse/PKG-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-675 Packaging tasks for release - PXC 8.4.5

percona-distribution-postgresql-13/Dockerfile.aarch64, percona-distribution-postgresql-14/Dockerfile.aarch64, percona-distribution-postgresql-15/Dockerfile.aarch64, percona-distribution-postgresql-16/Dockerfile.aarch64, percona-distribution-postgresql-17/Dockerfile.aarch64
[![PKG-891](https://badgen.net/badge/JIRA/PKG-891/green)](https://jira.percona.com/browse/PKG-891) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/PKG-891
[PKG-891]: https://perconadev.atlassian.net/browse/PKG-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-891 update gosu for arm64

fluentbit/Dockerfile
[![K8SPXC-1622](https://badgen.net/badge/JIRA/K8SPXC-1622/green)](https://jira.percona.com/browse/K8SPXC-1622) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1622]: https://perconadev.atlassian.net/browse/K8SPXC-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1622: use fluentbit 4.0.1

percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-16/Dockerfile
[![K8SPG-611](https://badgen.net/badge/JIRA/K8SPG-611/green)](https://jira.percona.com/browse/K8SPG-611) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-611
[K8SPG-611]: https://perconadev.atlassian.net/browse/K8SPG-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-611: update postgres 13,14,15,16 images

percona-server-mongodb-8.0/Dockerfile, percona-server-mongodb-8.0/Dockerfile-dockerhub, percona-server-mongodb-8.0/Dockerfile.aarch64, percona-server-mongodb-8.0/Dockerfile.k8s, percona-server-mongodb-8.0/Dockerfile.ubi8, percona-server-mongodb-8.0/Dockerfile.ubi9
[![PSMDB-1765](https://badgen.net/badge/JIRA/PSMDB-1765/green)](https://jira.percona.com/browse/PSMDB-1765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Approved by @radoslawszulgo to release with CVE-2025-47907
[PSMDB-1765]: https://perconadev.atlassian.net/browse/PSMDB-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSMDB-1765. Update psmdb-8.0 version

percona-server-8.4/Dockerfile, percona-server-8.4/dockerdir/usr/lib64/mysql/plugin/component_keyring_vault.cnf, percona-server-8.4/dockerdir/usr/sbin/mysqld.my
[![K8SPS-480](https://badgen.net/badge/JIRA/K8SPS-480/green)](https://jira.percona.com/browse/K8SPS-480) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPS-480]: https://perconadev.atlassian.net/browse/K8SPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-480: Add global manifest and keyring config

percona-server-8.4/Dockerfile, percona-server-8.4/Dockerfile.aarch64
[![PKG-1081](https://badgen.net/badge/JIRA/PKG-1081/green)](https://jira.percona.com/browse/PKG-1081) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-1081]: https://perconadev.atlassian.net/browse/PKG-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-1081 some files need to be added to percona server 8.4 image

percona-backup-mongodb/Dockerfile, percona-backup-mongodb/Dockerfile.aarch64, percona-backup-mongodb/Dockerfile.ubi8, percona-backup-mongodb/Dockerfile.ubi9
[![PBM-1620](https://badgen.net/badge/JIRA/PBM-1620/green)](https://jira.percona.com/browse/PBM-1620) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1620]: https://perconadev.atlassian.net/browse/PBM-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PBM-1620. Update pbm version

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.aarch64, percona-xtradb-cluster-8.0/Dockerfile.k8s, percona-xtradb-cluster-8.4/Dockerfile
[![PKG-1026](https://badgen.net/badge/JIRA/PKG-1026/green)](https://jira.percona.com/browse/PKG-1026) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-1026]: https://perconadev.atlassian.net/browse/PKG-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PKG-1026 Packaging tasks for release - PXC 8.4.6

percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile.aarch64, percona-xtradb-cluster-8.0/Dockerfile.k8s, percona-xtradb-cluster-8.4/Dockerfile, percona-xtradb-cluster-8.4/Dockerfile.aarch64, percona-xtradb-cluster-8.4/Dockerfile.k8s
[![PXC-4761](https://badgen.net/badge/JIRA/PXC-4761/green)](https://jira.percona.com/browse/PXC-4761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PXC-4761]: https://perconadev.atlassian.net/browse/PXC-4761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXC-4761 Add netcat as a dependency in PXC Docker images

percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-16/Dockerfile, percona-distribution-postgresql-17/Dockerfile, percona-pgbackrest/Dockerfile, percona-pgbouncer/Dockerfile, postgresql-containers/build/postgres-gis/Dockerfile
[![K8SPG-611](https://badgen.net/badge/JIRA/K8SPG-611/green)](https://jira.percona.com/browse/K8SPG-611) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPG-611]: https://perconadev.atlassian.net/browse/K8SPG-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-611 use official PG image

percona-xtrabackup-8.0/Dockerfile, percona-xtrabackup-8.x/Dockerfile, percona-xtradb-cluster-8.0/Dockerfile, percona-xtradb-cluster-8.4/Dockerfile
[![K8SPXC-1479](https://badgen.net/badge/JIRA/K8SPXC-1479/green)](https://jira.percona.com/browse/K8SPXC-1479) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPXC-1479]: https://perconadev.atlassian.net/browse/K8SPXC-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1479 add the possibility to set repo via '--build-arg' option

percona-distribution-postgresql-13/Dockerfile, percona-distribution-postgresql-13/Dockerfile.aarch64, percona-distribution-postgresql-14/Dockerfile, percona-distribution-postgresql-14/Dockerfile.aarch64, percona-distribution-postgresql-15/Dockerfile, percona-distribution-postgresql-15/Dockerfile.aarch64, percona-distribution-postgresql-16/Dockerfile, percona-distribution-postgresql-16/Dockerfile.aarch64, percona-distribution-postgresql-17/Dockerfile, percona-distribution-postgresql-17/Dockerfile.aarch64
[![PG-1937](https://badgen.net/badge/JIRA/PG-1937/green)](https://jira.percona.com/browse/PG-1937) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PG-1937]: https://perconadev.atlassian.net/browse/PG-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PG-1937 Invalid RedHats labels in Images - PPG
